package com.neu.his.dao;

import com.neu.his.model.DiseaseCategory;
import com.neu.his.model.DiseaseCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DiseaseCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease_category
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    long countByExample(DiseaseCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease_category
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    int deleteByExample(DiseaseCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease_category
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    int deleteByPrimaryKey(Short diseasecateid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease_category
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    int insert(DiseaseCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease_category
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    int insertSelective(DiseaseCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease_category
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    List<DiseaseCategory> selectByExample(DiseaseCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease_category
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    DiseaseCategory selectByPrimaryKey(Short diseasecateid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease_category
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    int updateByExampleSelective(@Param("record") DiseaseCategory record, @Param("example") DiseaseCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease_category
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    int updateByExample(@Param("record") DiseaseCategory record, @Param("example") DiseaseCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease_category
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    int updateByPrimaryKeySelective(DiseaseCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease_category
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    int updateByPrimaryKey(DiseaseCategory record);
}