package com.neu.his.dao;

import com.neu.his.pojo.DrugPrescription;
import com.neu.his.pojo.DrugPrescriptionExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface DrugPrescriptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_prescription
     *
     * @mbg.generated Thu Jul 25 15:12:20 CST 2019
     */
    long countByExample(DrugPrescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_prescription
     *
     * @mbg.generated Thu Jul 25 15:12:20 CST 2019
     */
    int deleteByExample(DrugPrescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_prescription
     *
     * @mbg.generated Thu Jul 25 15:12:20 CST 2019
     */
    int deleteByPrimaryKey(Integer drugPreId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_prescription
     *
     * @mbg.generated Thu Jul 25 15:12:20 CST 2019
     */
    int insert(DrugPrescription record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_prescription
     *
     * @mbg.generated Thu Jul 25 15:12:20 CST 2019
     */
    int insertSelective(DrugPrescription record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_prescription
     *
     * @mbg.generated Thu Jul 25 15:12:20 CST 2019
     */
    List<DrugPrescription> selectByExample(DrugPrescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_prescription
     *
     * @mbg.generated Thu Jul 25 15:12:20 CST 2019
     */
    DrugPrescription selectByPrimaryKey(Integer drugPreId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_prescription
     *
     * @mbg.generated Thu Jul 25 15:12:20 CST 2019
     */
    int updateByExampleSelective(@Param("record") DrugPrescription record, @Param("example") DrugPrescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_prescription
     *
     * @mbg.generated Thu Jul 25 15:12:20 CST 2019
     */
    int updateByExample(@Param("record") DrugPrescription record, @Param("example") DrugPrescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_prescription
     *
     * @mbg.generated Thu Jul 25 15:12:20 CST 2019
     */
    int updateByPrimaryKeySelective(DrugPrescription record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_prescription
     *
     * @mbg.generated Thu Jul 25 15:12:20 CST 2019
     */
    int updateByPrimaryKey(DrugPrescription record);

    /**
     * 找到最大ID
     *
     * @return
     */
    int findMaxPreId();
}