package com.neu.his.dao;

import com.neu.his.pojo.DrugTemplateDetail;
import com.neu.his.pojo.DrugTemplateDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DrugTemplateDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_template_detail
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    long countByExample(DrugTemplateDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_template_detail
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    int deleteByExample(DrugTemplateDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_template_detail
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    int deleteByPrimaryKey(Integer drugTempDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_template_detail
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    int insert(DrugTemplateDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_template_detail
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    int insertSelective(DrugTemplateDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_template_detail
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    List<DrugTemplateDetail> selectByExample(DrugTemplateDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_template_detail
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    DrugTemplateDetail selectByPrimaryKey(Integer drugTempDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_template_detail
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    int updateByExampleSelective(@Param("record") DrugTemplateDetail record, @Param("example") DrugTemplateDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_template_detail
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    int updateByExample(@Param("record") DrugTemplateDetail record, @Param("example") DrugTemplateDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_template_detail
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    int updateByPrimaryKeySelective(DrugTemplateDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_template_detail
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    int updateByPrimaryKey(DrugTemplateDetail record);
}