package com.neu.his.dao;

import com.neu.his.pojo.MedicalRecord;
import com.neu.his.pojo.MedicalRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface MedicalRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_record
     *
     * @mbg.generated Wed Jul 24 16:08:55 CST 2019
     */
    long countByExample(MedicalRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_record
     *
     * @mbg.generated Wed Jul 24 16:08:55 CST 2019
     */
    int deleteByExample(MedicalRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_record
     *
     * @mbg.generated Wed Jul 24 16:08:55 CST 2019
     */
    int deleteByPrimaryKey(Integer medicalRegistId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_record
     *
     * @mbg.generated Wed Jul 24 16:08:55 CST 2019
     */
    int insert(MedicalRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_record
     *
     * @mbg.generated Wed Jul 24 16:08:55 CST 2019
     */
    int insertSelective(MedicalRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_record
     *
     * @mbg.generated Wed Jul 24 16:08:55 CST 2019
     */
    List<MedicalRecord> selectByExample(MedicalRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_record
     *
     * @mbg.generated Wed Jul 24 16:08:55 CST 2019
     */
    MedicalRecord selectByPrimaryKey(Integer medicalRegistId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_record
     *
     * @mbg.generated Wed Jul 24 16:08:55 CST 2019
     */
    int updateByExampleSelective(@Param("record") MedicalRecord record, @Param("example") MedicalRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_record
     *
     * @mbg.generated Wed Jul 24 16:08:55 CST 2019
     */
    int updateByExample(@Param("record") MedicalRecord record, @Param("example") MedicalRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_record
     *
     * @mbg.generated Wed Jul 24 16:08:55 CST 2019
     */
    int updateByPrimaryKeySelective(MedicalRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_record
     *
     * @mbg.generated Wed Jul 24 16:08:55 CST 2019
     */
    int updateByPrimaryKey(MedicalRecord record);
}