package com.neu.his.dao;

import com.neu.his.pojo.MedicalRecord;
import com.neu.his.pojo.MedicalRecordExample;
import com.neu.his.pojo.MedicalRecordWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MedicalRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_record
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    long countByExample(MedicalRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_record
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    int deleteByExample(MedicalRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_record
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    int deleteByPrimaryKey(Integer medicalRegistId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_record
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    int insert(MedicalRecordWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_record
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    int insertSelective(MedicalRecordWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_record
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    List<MedicalRecordWithBLOBs> selectByExampleWithBLOBs(MedicalRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_record
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    List<MedicalRecord> selectByExample(MedicalRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_record
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    MedicalRecordWithBLOBs selectByPrimaryKey(Integer medicalRegistId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_record
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    int updateByExampleSelective(@Param("record") MedicalRecordWithBLOBs record, @Param("example") MedicalRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_record
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") MedicalRecordWithBLOBs record, @Param("example") MedicalRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_record
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    int updateByExample(@Param("record") MedicalRecord record, @Param("example") MedicalRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_record
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    int updateByPrimaryKeySelective(MedicalRecordWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_record
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(MedicalRecordWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_record
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    int updateByPrimaryKey(MedicalRecord record);
}