package com.neu.his.dao;

import com.neu.his.model.NonDrugItem;
import com.neu.his.model.NonDrugItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NonDrugItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table non_drug_item
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    long countByExample(NonDrugItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table non_drug_item
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    int deleteByExample(NonDrugItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table non_drug_item
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    int deleteByPrimaryKey(Short itemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table non_drug_item
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    int insert(NonDrugItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table non_drug_item
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    int insertSelective(NonDrugItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table non_drug_item
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    List<NonDrugItem> selectByExample(NonDrugItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table non_drug_item
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    NonDrugItem selectByPrimaryKey(Short itemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table non_drug_item
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    int updateByExampleSelective(@Param("record") NonDrugItem record, @Param("example") NonDrugItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table non_drug_item
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    int updateByExample(@Param("record") NonDrugItem record, @Param("example") NonDrugItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table non_drug_item
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    int updateByPrimaryKeySelective(NonDrugItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table non_drug_item
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    int updateByPrimaryKey(NonDrugItem record);
}