package com.neu.his.dao;

import com.neu.his.pojo.RegistrationRecord;
import com.neu.his.pojo.RegistrationRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface RegistrationRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration_record
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    long countByExample(RegistrationRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration_record
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    int deleteByExample(RegistrationRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration_record
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    int deleteByPrimaryKey(Integer registId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration_record
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    int insert(RegistrationRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration_record
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    int insertSelective(RegistrationRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration_record
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    List<RegistrationRecord> selectByExample(RegistrationRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration_record
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    RegistrationRecord selectByPrimaryKey(Integer registId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration_record
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    int updateByExampleSelective(@Param("record") RegistrationRecord record, @Param("example") RegistrationRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration_record
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    int updateByExample(@Param("record") RegistrationRecord record, @Param("example") RegistrationRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration_record
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    int updateByPrimaryKeySelective(RegistrationRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration_record
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    int updateByPrimaryKey(RegistrationRecord record);
}