package com.neu.his.dao;

import com.neu.his.model.Settlement;
import com.neu.his.model.SettlementExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SettlementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlement
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    long countByExample(SettlementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlement
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    int deleteByExample(SettlementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlement
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    int deleteByPrimaryKey(Integer settlementid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlement
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    int insert(Settlement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlement
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    int insertSelective(Settlement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlement
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    List<Settlement> selectByExample(SettlementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlement
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    Settlement selectByPrimaryKey(Integer settlementid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlement
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    int updateByExampleSelective(@Param("record") Settlement record, @Param("example") SettlementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlement
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    int updateByExample(@Param("record") Settlement record, @Param("example") SettlementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlement
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    int updateByPrimaryKeySelective(Settlement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlement
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    int updateByPrimaryKey(Settlement record);
}