package com.neu.his.model;

import java.util.ArrayList;
import java.util.List;

public class ChargeSubjectExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table charge_subject
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table charge_subject
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table charge_subject
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_subject
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public ChargeSubjectExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_subject
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_subject
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_subject
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_subject
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_subject
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_subject
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_subject
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_subject
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_subject
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_subject
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table charge_subject
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andChargesubjectidIsNull() {
            addCriterion("chargeSubjectID is null");
            return (Criteria) this;
        }

        public Criteria andChargesubjectidIsNotNull() {
            addCriterion("chargeSubjectID is not null");
            return (Criteria) this;
        }

        public Criteria andChargesubjectidEqualTo(Byte value) {
            addCriterion("chargeSubjectID =", value, "chargesubjectid");
            return (Criteria) this;
        }

        public Criteria andChargesubjectidNotEqualTo(Byte value) {
            addCriterion("chargeSubjectID <>", value, "chargesubjectid");
            return (Criteria) this;
        }

        public Criteria andChargesubjectidGreaterThan(Byte value) {
            addCriterion("chargeSubjectID >", value, "chargesubjectid");
            return (Criteria) this;
        }

        public Criteria andChargesubjectidGreaterThanOrEqualTo(Byte value) {
            addCriterion("chargeSubjectID >=", value, "chargesubjectid");
            return (Criteria) this;
        }

        public Criteria andChargesubjectidLessThan(Byte value) {
            addCriterion("chargeSubjectID <", value, "chargesubjectid");
            return (Criteria) this;
        }

        public Criteria andChargesubjectidLessThanOrEqualTo(Byte value) {
            addCriterion("chargeSubjectID <=", value, "chargesubjectid");
            return (Criteria) this;
        }

        public Criteria andChargesubjectidIn(List<Byte> values) {
            addCriterion("chargeSubjectID in", values, "chargesubjectid");
            return (Criteria) this;
        }

        public Criteria andChargesubjectidNotIn(List<Byte> values) {
            addCriterion("chargeSubjectID not in", values, "chargesubjectid");
            return (Criteria) this;
        }

        public Criteria andChargesubjectidBetween(Byte value1, Byte value2) {
            addCriterion("chargeSubjectID between", value1, value2, "chargesubjectid");
            return (Criteria) this;
        }

        public Criteria andChargesubjectidNotBetween(Byte value1, Byte value2) {
            addCriterion("chargeSubjectID not between", value1, value2, "chargesubjectid");
            return (Criteria) this;
        }

        public Criteria andChargesubjectnameIsNull() {
            addCriterion("chargeSubjectName is null");
            return (Criteria) this;
        }

        public Criteria andChargesubjectnameIsNotNull() {
            addCriterion("chargeSubjectName is not null");
            return (Criteria) this;
        }

        public Criteria andChargesubjectnameEqualTo(String value) {
            addCriterion("chargeSubjectName =", value, "chargesubjectname");
            return (Criteria) this;
        }

        public Criteria andChargesubjectnameNotEqualTo(String value) {
            addCriterion("chargeSubjectName <>", value, "chargesubjectname");
            return (Criteria) this;
        }

        public Criteria andChargesubjectnameGreaterThan(String value) {
            addCriterion("chargeSubjectName >", value, "chargesubjectname");
            return (Criteria) this;
        }

        public Criteria andChargesubjectnameGreaterThanOrEqualTo(String value) {
            addCriterion("chargeSubjectName >=", value, "chargesubjectname");
            return (Criteria) this;
        }

        public Criteria andChargesubjectnameLessThan(String value) {
            addCriterion("chargeSubjectName <", value, "chargesubjectname");
            return (Criteria) this;
        }

        public Criteria andChargesubjectnameLessThanOrEqualTo(String value) {
            addCriterion("chargeSubjectName <=", value, "chargesubjectname");
            return (Criteria) this;
        }

        public Criteria andChargesubjectnameLike(String value) {
            addCriterion("chargeSubjectName like", value, "chargesubjectname");
            return (Criteria) this;
        }

        public Criteria andChargesubjectnameNotLike(String value) {
            addCriterion("chargeSubjectName not like", value, "chargesubjectname");
            return (Criteria) this;
        }

        public Criteria andChargesubjectnameIn(List<String> values) {
            addCriterion("chargeSubjectName in", values, "chargesubjectname");
            return (Criteria) this;
        }

        public Criteria andChargesubjectnameNotIn(List<String> values) {
            addCriterion("chargeSubjectName not in", values, "chargesubjectname");
            return (Criteria) this;
        }

        public Criteria andChargesubjectnameBetween(String value1, String value2) {
            addCriterion("chargeSubjectName between", value1, value2, "chargesubjectname");
            return (Criteria) this;
        }

        public Criteria andChargesubjectnameNotBetween(String value1, String value2) {
            addCriterion("chargeSubjectName not between", value1, value2, "chargesubjectname");
            return (Criteria) this;
        }

        public Criteria andChargesubjectcodeIsNull() {
            addCriterion("chargeSubjectCode is null");
            return (Criteria) this;
        }

        public Criteria andChargesubjectcodeIsNotNull() {
            addCriterion("chargeSubjectCode is not null");
            return (Criteria) this;
        }

        public Criteria andChargesubjectcodeEqualTo(String value) {
            addCriterion("chargeSubjectCode =", value, "chargesubjectcode");
            return (Criteria) this;
        }

        public Criteria andChargesubjectcodeNotEqualTo(String value) {
            addCriterion("chargeSubjectCode <>", value, "chargesubjectcode");
            return (Criteria) this;
        }

        public Criteria andChargesubjectcodeGreaterThan(String value) {
            addCriterion("chargeSubjectCode >", value, "chargesubjectcode");
            return (Criteria) this;
        }

        public Criteria andChargesubjectcodeGreaterThanOrEqualTo(String value) {
            addCriterion("chargeSubjectCode >=", value, "chargesubjectcode");
            return (Criteria) this;
        }

        public Criteria andChargesubjectcodeLessThan(String value) {
            addCriterion("chargeSubjectCode <", value, "chargesubjectcode");
            return (Criteria) this;
        }

        public Criteria andChargesubjectcodeLessThanOrEqualTo(String value) {
            addCriterion("chargeSubjectCode <=", value, "chargesubjectcode");
            return (Criteria) this;
        }

        public Criteria andChargesubjectcodeLike(String value) {
            addCriterion("chargeSubjectCode like", value, "chargesubjectcode");
            return (Criteria) this;
        }

        public Criteria andChargesubjectcodeNotLike(String value) {
            addCriterion("chargeSubjectCode not like", value, "chargesubjectcode");
            return (Criteria) this;
        }

        public Criteria andChargesubjectcodeIn(List<String> values) {
            addCriterion("chargeSubjectCode in", values, "chargesubjectcode");
            return (Criteria) this;
        }

        public Criteria andChargesubjectcodeNotIn(List<String> values) {
            addCriterion("chargeSubjectCode not in", values, "chargesubjectcode");
            return (Criteria) this;
        }

        public Criteria andChargesubjectcodeBetween(String value1, String value2) {
            addCriterion("chargeSubjectCode between", value1, value2, "chargesubjectcode");
            return (Criteria) this;
        }

        public Criteria andChargesubjectcodeNotBetween(String value1, String value2) {
            addCriterion("chargeSubjectCode not between", value1, value2, "chargesubjectcode");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table charge_subject
     *
     * @mbg.generated do_not_delete_during_merge Mon Jul 22 15:20:08 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table charge_subject
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}