package com.neu.his.model;

public class Department {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.deptID
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    private Short deptid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.deptCode
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    private String deptcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.deptName
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    private String deptname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.deptCategory
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    private Byte deptcategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.deptType
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    private Boolean depttype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.deptID
     *
     * @return the value of department.deptID
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public Short getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.deptID
     *
     * @param deptid the value for department.deptID
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public void setDeptid(Short deptid) {
        this.deptid = deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.deptCode
     *
     * @return the value of department.deptCode
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public String getDeptcode() {
        return deptcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.deptCode
     *
     * @param deptcode the value for department.deptCode
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public void setDeptcode(String deptcode) {
        this.deptcode = deptcode == null ? null : deptcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.deptName
     *
     * @return the value of department.deptName
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public String getDeptname() {
        return deptname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.deptName
     *
     * @param deptname the value for department.deptName
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public void setDeptname(String deptname) {
        this.deptname = deptname == null ? null : deptname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.deptCategory
     *
     * @return the value of department.deptCategory
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public Byte getDeptcategory() {
        return deptcategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.deptCategory
     *
     * @param deptcategory the value for department.deptCategory
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public void setDeptcategory(Byte deptcategory) {
        this.deptcategory = deptcategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.deptType
     *
     * @return the value of department.deptType
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public Boolean getDepttype() {
        return depttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.deptType
     *
     * @param depttype the value for department.deptType
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public void setDepttype(Boolean depttype) {
        this.depttype = depttype;
    }
}