package com.neu.his.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DrugPrescriptionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table drug_prescription
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table drug_prescription
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table drug_prescription
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_prescription
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public DrugPrescriptionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_prescription
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_prescription
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_prescription
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_prescription
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_prescription
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_prescription
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_prescription
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_prescription
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_prescription
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_prescription
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table drug_prescription
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDrugpreidIsNull() {
            addCriterion("drugPreID is null");
            return (Criteria) this;
        }

        public Criteria andDrugpreidIsNotNull() {
            addCriterion("drugPreID is not null");
            return (Criteria) this;
        }

        public Criteria andDrugpreidEqualTo(Integer value) {
            addCriterion("drugPreID =", value, "drugpreid");
            return (Criteria) this;
        }

        public Criteria andDrugpreidNotEqualTo(Integer value) {
            addCriterion("drugPreID <>", value, "drugpreid");
            return (Criteria) this;
        }

        public Criteria andDrugpreidGreaterThan(Integer value) {
            addCriterion("drugPreID >", value, "drugpreid");
            return (Criteria) this;
        }

        public Criteria andDrugpreidGreaterThanOrEqualTo(Integer value) {
            addCriterion("drugPreID >=", value, "drugpreid");
            return (Criteria) this;
        }

        public Criteria andDrugpreidLessThan(Integer value) {
            addCriterion("drugPreID <", value, "drugpreid");
            return (Criteria) this;
        }

        public Criteria andDrugpreidLessThanOrEqualTo(Integer value) {
            addCriterion("drugPreID <=", value, "drugpreid");
            return (Criteria) this;
        }

        public Criteria andDrugpreidIn(List<Integer> values) {
            addCriterion("drugPreID in", values, "drugpreid");
            return (Criteria) this;
        }

        public Criteria andDrugpreidNotIn(List<Integer> values) {
            addCriterion("drugPreID not in", values, "drugpreid");
            return (Criteria) this;
        }

        public Criteria andDrugpreidBetween(Integer value1, Integer value2) {
            addCriterion("drugPreID between", value1, value2, "drugpreid");
            return (Criteria) this;
        }

        public Criteria andDrugpreidNotBetween(Integer value1, Integer value2) {
            addCriterion("drugPreID not between", value1, value2, "drugpreid");
            return (Criteria) this;
        }

        public Criteria andRegistidIsNull() {
            addCriterion("registID is null");
            return (Criteria) this;
        }

        public Criteria andRegistidIsNotNull() {
            addCriterion("registID is not null");
            return (Criteria) this;
        }

        public Criteria andRegistidEqualTo(Integer value) {
            addCriterion("registID =", value, "registid");
            return (Criteria) this;
        }

        public Criteria andRegistidNotEqualTo(Integer value) {
            addCriterion("registID <>", value, "registid");
            return (Criteria) this;
        }

        public Criteria andRegistidGreaterThan(Integer value) {
            addCriterion("registID >", value, "registid");
            return (Criteria) this;
        }

        public Criteria andRegistidGreaterThanOrEqualTo(Integer value) {
            addCriterion("registID >=", value, "registid");
            return (Criteria) this;
        }

        public Criteria andRegistidLessThan(Integer value) {
            addCriterion("registID <", value, "registid");
            return (Criteria) this;
        }

        public Criteria andRegistidLessThanOrEqualTo(Integer value) {
            addCriterion("registID <=", value, "registid");
            return (Criteria) this;
        }

        public Criteria andRegistidIn(List<Integer> values) {
            addCriterion("registID in", values, "registid");
            return (Criteria) this;
        }

        public Criteria andRegistidNotIn(List<Integer> values) {
            addCriterion("registID not in", values, "registid");
            return (Criteria) this;
        }

        public Criteria andRegistidBetween(Integer value1, Integer value2) {
            addCriterion("registID between", value1, value2, "registid");
            return (Criteria) this;
        }

        public Criteria andRegistidNotBetween(Integer value1, Integer value2) {
            addCriterion("registID not between", value1, value2, "registid");
            return (Criteria) this;
        }

        public Criteria andDoctoridIsNull() {
            addCriterion("doctorID is null");
            return (Criteria) this;
        }

        public Criteria andDoctoridIsNotNull() {
            addCriterion("doctorID is not null");
            return (Criteria) this;
        }

        public Criteria andDoctoridEqualTo(Short value) {
            addCriterion("doctorID =", value, "doctorid");
            return (Criteria) this;
        }

        public Criteria andDoctoridNotEqualTo(Short value) {
            addCriterion("doctorID <>", value, "doctorid");
            return (Criteria) this;
        }

        public Criteria andDoctoridGreaterThan(Short value) {
            addCriterion("doctorID >", value, "doctorid");
            return (Criteria) this;
        }

        public Criteria andDoctoridGreaterThanOrEqualTo(Short value) {
            addCriterion("doctorID >=", value, "doctorid");
            return (Criteria) this;
        }

        public Criteria andDoctoridLessThan(Short value) {
            addCriterion("doctorID <", value, "doctorid");
            return (Criteria) this;
        }

        public Criteria andDoctoridLessThanOrEqualTo(Short value) {
            addCriterion("doctorID <=", value, "doctorid");
            return (Criteria) this;
        }

        public Criteria andDoctoridIn(List<Short> values) {
            addCriterion("doctorID in", values, "doctorid");
            return (Criteria) this;
        }

        public Criteria andDoctoridNotIn(List<Short> values) {
            addCriterion("doctorID not in", values, "doctorid");
            return (Criteria) this;
        }

        public Criteria andDoctoridBetween(Short value1, Short value2) {
            addCriterion("doctorID between", value1, value2, "doctorid");
            return (Criteria) this;
        }

        public Criteria andDoctoridNotBetween(Short value1, Short value2) {
            addCriterion("doctorID not between", value1, value2, "doctorid");
            return (Criteria) this;
        }

        public Criteria andMedicalrecordidIsNull() {
            addCriterion("medicalRecordID is null");
            return (Criteria) this;
        }

        public Criteria andMedicalrecordidIsNotNull() {
            addCriterion("medicalRecordID is not null");
            return (Criteria) this;
        }

        public Criteria andMedicalrecordidEqualTo(Integer value) {
            addCriterion("medicalRecordID =", value, "medicalrecordid");
            return (Criteria) this;
        }

        public Criteria andMedicalrecordidNotEqualTo(Integer value) {
            addCriterion("medicalRecordID <>", value, "medicalrecordid");
            return (Criteria) this;
        }

        public Criteria andMedicalrecordidGreaterThan(Integer value) {
            addCriterion("medicalRecordID >", value, "medicalrecordid");
            return (Criteria) this;
        }

        public Criteria andMedicalrecordidGreaterThanOrEqualTo(Integer value) {
            addCriterion("medicalRecordID >=", value, "medicalrecordid");
            return (Criteria) this;
        }

        public Criteria andMedicalrecordidLessThan(Integer value) {
            addCriterion("medicalRecordID <", value, "medicalrecordid");
            return (Criteria) this;
        }

        public Criteria andMedicalrecordidLessThanOrEqualTo(Integer value) {
            addCriterion("medicalRecordID <=", value, "medicalrecordid");
            return (Criteria) this;
        }

        public Criteria andMedicalrecordidIn(List<Integer> values) {
            addCriterion("medicalRecordID in", values, "medicalrecordid");
            return (Criteria) this;
        }

        public Criteria andMedicalrecordidNotIn(List<Integer> values) {
            addCriterion("medicalRecordID not in", values, "medicalrecordid");
            return (Criteria) this;
        }

        public Criteria andMedicalrecordidBetween(Integer value1, Integer value2) {
            addCriterion("medicalRecordID between", value1, value2, "medicalrecordid");
            return (Criteria) this;
        }

        public Criteria andMedicalrecordidNotBetween(Integer value1, Integer value2) {
            addCriterion("medicalRecordID not between", value1, value2, "medicalrecordid");
            return (Criteria) this;
        }

        public Criteria andDrugprenameIsNull() {
            addCriterion("drugPreName is null");
            return (Criteria) this;
        }

        public Criteria andDrugprenameIsNotNull() {
            addCriterion("drugPreName is not null");
            return (Criteria) this;
        }

        public Criteria andDrugprenameEqualTo(String value) {
            addCriterion("drugPreName =", value, "drugprename");
            return (Criteria) this;
        }

        public Criteria andDrugprenameNotEqualTo(String value) {
            addCriterion("drugPreName <>", value, "drugprename");
            return (Criteria) this;
        }

        public Criteria andDrugprenameGreaterThan(String value) {
            addCriterion("drugPreName >", value, "drugprename");
            return (Criteria) this;
        }

        public Criteria andDrugprenameGreaterThanOrEqualTo(String value) {
            addCriterion("drugPreName >=", value, "drugprename");
            return (Criteria) this;
        }

        public Criteria andDrugprenameLessThan(String value) {
            addCriterion("drugPreName <", value, "drugprename");
            return (Criteria) this;
        }

        public Criteria andDrugprenameLessThanOrEqualTo(String value) {
            addCriterion("drugPreName <=", value, "drugprename");
            return (Criteria) this;
        }

        public Criteria andDrugprenameLike(String value) {
            addCriterion("drugPreName like", value, "drugprename");
            return (Criteria) this;
        }

        public Criteria andDrugprenameNotLike(String value) {
            addCriterion("drugPreName not like", value, "drugprename");
            return (Criteria) this;
        }

        public Criteria andDrugprenameIn(List<String> values) {
            addCriterion("drugPreName in", values, "drugprename");
            return (Criteria) this;
        }

        public Criteria andDrugprenameNotIn(List<String> values) {
            addCriterion("drugPreName not in", values, "drugprename");
            return (Criteria) this;
        }

        public Criteria andDrugprenameBetween(String value1, String value2) {
            addCriterion("drugPreName between", value1, value2, "drugprename");
            return (Criteria) this;
        }

        public Criteria andDrugprenameNotBetween(String value1, String value2) {
            addCriterion("drugPreName not between", value1, value2, "drugprename");
            return (Criteria) this;
        }

        public Criteria andDrugpretimeIsNull() {
            addCriterion("drugPreTime is null");
            return (Criteria) this;
        }

        public Criteria andDrugpretimeIsNotNull() {
            addCriterion("drugPreTime is not null");
            return (Criteria) this;
        }

        public Criteria andDrugpretimeEqualTo(Date value) {
            addCriterion("drugPreTime =", value, "drugpretime");
            return (Criteria) this;
        }

        public Criteria andDrugpretimeNotEqualTo(Date value) {
            addCriterion("drugPreTime <>", value, "drugpretime");
            return (Criteria) this;
        }

        public Criteria andDrugpretimeGreaterThan(Date value) {
            addCriterion("drugPreTime >", value, "drugpretime");
            return (Criteria) this;
        }

        public Criteria andDrugpretimeGreaterThanOrEqualTo(Date value) {
            addCriterion("drugPreTime >=", value, "drugpretime");
            return (Criteria) this;
        }

        public Criteria andDrugpretimeLessThan(Date value) {
            addCriterion("drugPreTime <", value, "drugpretime");
            return (Criteria) this;
        }

        public Criteria andDrugpretimeLessThanOrEqualTo(Date value) {
            addCriterion("drugPreTime <=", value, "drugpretime");
            return (Criteria) this;
        }

        public Criteria andDrugpretimeIn(List<Date> values) {
            addCriterion("drugPreTime in", values, "drugpretime");
            return (Criteria) this;
        }

        public Criteria andDrugpretimeNotIn(List<Date> values) {
            addCriterion("drugPreTime not in", values, "drugpretime");
            return (Criteria) this;
        }

        public Criteria andDrugpretimeBetween(Date value1, Date value2) {
            addCriterion("drugPreTime between", value1, value2, "drugpretime");
            return (Criteria) this;
        }

        public Criteria andDrugpretimeNotBetween(Date value1, Date value2) {
            addCriterion("drugPreTime not between", value1, value2, "drugpretime");
            return (Criteria) this;
        }

        public Criteria andDrugprestateIsNull() {
            addCriterion("drugPreState is null");
            return (Criteria) this;
        }

        public Criteria andDrugprestateIsNotNull() {
            addCriterion("drugPreState is not null");
            return (Criteria) this;
        }

        public Criteria andDrugprestateEqualTo(String value) {
            addCriterion("drugPreState =", value, "drugprestate");
            return (Criteria) this;
        }

        public Criteria andDrugprestateNotEqualTo(String value) {
            addCriterion("drugPreState <>", value, "drugprestate");
            return (Criteria) this;
        }

        public Criteria andDrugprestateGreaterThan(String value) {
            addCriterion("drugPreState >", value, "drugprestate");
            return (Criteria) this;
        }

        public Criteria andDrugprestateGreaterThanOrEqualTo(String value) {
            addCriterion("drugPreState >=", value, "drugprestate");
            return (Criteria) this;
        }

        public Criteria andDrugprestateLessThan(String value) {
            addCriterion("drugPreState <", value, "drugprestate");
            return (Criteria) this;
        }

        public Criteria andDrugprestateLessThanOrEqualTo(String value) {
            addCriterion("drugPreState <=", value, "drugprestate");
            return (Criteria) this;
        }

        public Criteria andDrugprestateLike(String value) {
            addCriterion("drugPreState like", value, "drugprestate");
            return (Criteria) this;
        }

        public Criteria andDrugprestateNotLike(String value) {
            addCriterion("drugPreState not like", value, "drugprestate");
            return (Criteria) this;
        }

        public Criteria andDrugprestateIn(List<String> values) {
            addCriterion("drugPreState in", values, "drugprestate");
            return (Criteria) this;
        }

        public Criteria andDrugprestateNotIn(List<String> values) {
            addCriterion("drugPreState not in", values, "drugprestate");
            return (Criteria) this;
        }

        public Criteria andDrugprestateBetween(String value1, String value2) {
            addCriterion("drugPreState between", value1, value2, "drugprestate");
            return (Criteria) this;
        }

        public Criteria andDrugprestateNotBetween(String value1, String value2) {
            addCriterion("drugPreState not between", value1, value2, "drugprestate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table drug_prescription
     *
     * @mbg.generated do_not_delete_during_merge Mon Jul 22 15:20:08 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table drug_prescription
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}