package com.neu.his.model;

import java.util.Date;

public class Invoice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.invoiceID
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    private Integer invoiceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.invoicePrice
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    private Float invoiceprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.invoiceState
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    private Boolean invoicestate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.invoiceOperaTime
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    private Date invoiceoperatime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.chargeUserID
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    private Short chargeuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.registID
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    private Integer registid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.chargeType
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    private Boolean chargetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.invoiceRedID
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    private Integer invoiceredid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.invoiceSettleState
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    private Boolean invoicesettlestate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.invoiceID
     *
     * @return the value of invoice.invoiceID
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public Integer getInvoiceid() {
        return invoiceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.invoiceID
     *
     * @param invoiceid the value for invoice.invoiceID
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public void setInvoiceid(Integer invoiceid) {
        this.invoiceid = invoiceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.invoicePrice
     *
     * @return the value of invoice.invoicePrice
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public Float getInvoiceprice() {
        return invoiceprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.invoicePrice
     *
     * @param invoiceprice the value for invoice.invoicePrice
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public void setInvoiceprice(Float invoiceprice) {
        this.invoiceprice = invoiceprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.invoiceState
     *
     * @return the value of invoice.invoiceState
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public Boolean getInvoicestate() {
        return invoicestate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.invoiceState
     *
     * @param invoicestate the value for invoice.invoiceState
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public void setInvoicestate(Boolean invoicestate) {
        this.invoicestate = invoicestate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.invoiceOperaTime
     *
     * @return the value of invoice.invoiceOperaTime
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public Date getInvoiceoperatime() {
        return invoiceoperatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.invoiceOperaTime
     *
     * @param invoiceoperatime the value for invoice.invoiceOperaTime
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public void setInvoiceoperatime(Date invoiceoperatime) {
        this.invoiceoperatime = invoiceoperatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.chargeUserID
     *
     * @return the value of invoice.chargeUserID
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public Short getChargeuserid() {
        return chargeuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.chargeUserID
     *
     * @param chargeuserid the value for invoice.chargeUserID
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public void setChargeuserid(Short chargeuserid) {
        this.chargeuserid = chargeuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.registID
     *
     * @return the value of invoice.registID
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public Integer getRegistid() {
        return registid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.registID
     *
     * @param registid the value for invoice.registID
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public void setRegistid(Integer registid) {
        this.registid = registid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.chargeType
     *
     * @return the value of invoice.chargeType
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public Boolean getChargetype() {
        return chargetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.chargeType
     *
     * @param chargetype the value for invoice.chargeType
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public void setChargetype(Boolean chargetype) {
        this.chargetype = chargetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.invoiceRedID
     *
     * @return the value of invoice.invoiceRedID
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public Integer getInvoiceredid() {
        return invoiceredid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.invoiceRedID
     *
     * @param invoiceredid the value for invoice.invoiceRedID
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public void setInvoiceredid(Integer invoiceredid) {
        this.invoiceredid = invoiceredid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.invoiceSettleState
     *
     * @return the value of invoice.invoiceSettleState
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public Boolean getInvoicesettlestate() {
        return invoicesettlestate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.invoiceSettleState
     *
     * @param invoicesettlestate the value for invoice.invoiceSettleState
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public void setInvoicesettlestate(Boolean invoicesettlestate) {
        this.invoicesettlestate = invoicesettlestate;
    }
}