package com.neu.his.model;

public class MedicalRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medical_record.medicalRegistID
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    private Integer medicalregistid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medical_record.medicalRecordState
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    private String medicalrecordstate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_record.medicalRegistID
     *
     * @return the value of medical_record.medicalRegistID
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public Integer getMedicalregistid() {
        return medicalregistid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_record.medicalRegistID
     *
     * @param medicalregistid the value for medical_record.medicalRegistID
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public void setMedicalregistid(Integer medicalregistid) {
        this.medicalregistid = medicalregistid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_record.medicalRecordState
     *
     * @return the value of medical_record.medicalRecordState
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public String getMedicalrecordstate() {
        return medicalrecordstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_record.medicalRecordState
     *
     * @param medicalrecordstate the value for medical_record.medicalRecordState
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public void setMedicalrecordstate(String medicalrecordstate) {
        this.medicalrecordstate = medicalrecordstate == null ? null : medicalrecordstate.trim();
    }
}