package com.neu.his.model;

import java.util.Date;

public class NonDrugItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column non_drug_item.itemID
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    private Short itemid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column non_drug_item.itemCode
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    private String itemcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column non_drug_item.itemName
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    private String itemname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column non_drug_item.itemSpecif
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    private String itemspecif;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column non_drug_item.itemPrice
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    private Float itemprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column non_drug_item.chargeSubjectCode
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    private Byte chargesubjectcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column non_drug_item.deptID
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    private Short deptid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column non_drug_item.itemType
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    private Boolean itemtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column non_drug_item.itemCrtTime
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    private Date itemcrttime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column non_drug_item.itemID
     *
     * @return the value of non_drug_item.itemID
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public Short getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column non_drug_item.itemID
     *
     * @param itemid the value for non_drug_item.itemID
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public void setItemid(Short itemid) {
        this.itemid = itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column non_drug_item.itemCode
     *
     * @return the value of non_drug_item.itemCode
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public String getItemcode() {
        return itemcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column non_drug_item.itemCode
     *
     * @param itemcode the value for non_drug_item.itemCode
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public void setItemcode(String itemcode) {
        this.itemcode = itemcode == null ? null : itemcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column non_drug_item.itemName
     *
     * @return the value of non_drug_item.itemName
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public String getItemname() {
        return itemname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column non_drug_item.itemName
     *
     * @param itemname the value for non_drug_item.itemName
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public void setItemname(String itemname) {
        this.itemname = itemname == null ? null : itemname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column non_drug_item.itemSpecif
     *
     * @return the value of non_drug_item.itemSpecif
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public String getItemspecif() {
        return itemspecif;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column non_drug_item.itemSpecif
     *
     * @param itemspecif the value for non_drug_item.itemSpecif
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public void setItemspecif(String itemspecif) {
        this.itemspecif = itemspecif == null ? null : itemspecif.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column non_drug_item.itemPrice
     *
     * @return the value of non_drug_item.itemPrice
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public Float getItemprice() {
        return itemprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column non_drug_item.itemPrice
     *
     * @param itemprice the value for non_drug_item.itemPrice
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public void setItemprice(Float itemprice) {
        this.itemprice = itemprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column non_drug_item.chargeSubjectCode
     *
     * @return the value of non_drug_item.chargeSubjectCode
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public Byte getChargesubjectcode() {
        return chargesubjectcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column non_drug_item.chargeSubjectCode
     *
     * @param chargesubjectcode the value for non_drug_item.chargeSubjectCode
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public void setChargesubjectcode(Byte chargesubjectcode) {
        this.chargesubjectcode = chargesubjectcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column non_drug_item.deptID
     *
     * @return the value of non_drug_item.deptID
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public Short getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column non_drug_item.deptID
     *
     * @param deptid the value for non_drug_item.deptID
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public void setDeptid(Short deptid) {
        this.deptid = deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column non_drug_item.itemType
     *
     * @return the value of non_drug_item.itemType
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public Boolean getItemtype() {
        return itemtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column non_drug_item.itemType
     *
     * @param itemtype the value for non_drug_item.itemType
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public void setItemtype(Boolean itemtype) {
        this.itemtype = itemtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column non_drug_item.itemCrtTime
     *
     * @return the value of non_drug_item.itemCrtTime
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public Date getItemcrttime() {
        return itemcrttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column non_drug_item.itemCrtTime
     *
     * @param itemcrttime the value for non_drug_item.itemCrtTime
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public void setItemcrttime(Date itemcrttime) {
        this.itemcrttime = itemcrttime;
    }
}