package com.neu.his.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class NonDrugItemExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table non_drug_item
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table non_drug_item
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table non_drug_item
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table non_drug_item
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public NonDrugItemExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table non_drug_item
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table non_drug_item
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table non_drug_item
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table non_drug_item
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table non_drug_item
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table non_drug_item
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table non_drug_item
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table non_drug_item
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table non_drug_item
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table non_drug_item
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table non_drug_item
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andItemidIsNull() {
            addCriterion("itemID is null");
            return (Criteria) this;
        }

        public Criteria andItemidIsNotNull() {
            addCriterion("itemID is not null");
            return (Criteria) this;
        }

        public Criteria andItemidEqualTo(Short value) {
            addCriterion("itemID =", value, "itemid");
            return (Criteria) this;
        }

        public Criteria andItemidNotEqualTo(Short value) {
            addCriterion("itemID <>", value, "itemid");
            return (Criteria) this;
        }

        public Criteria andItemidGreaterThan(Short value) {
            addCriterion("itemID >", value, "itemid");
            return (Criteria) this;
        }

        public Criteria andItemidGreaterThanOrEqualTo(Short value) {
            addCriterion("itemID >=", value, "itemid");
            return (Criteria) this;
        }

        public Criteria andItemidLessThan(Short value) {
            addCriterion("itemID <", value, "itemid");
            return (Criteria) this;
        }

        public Criteria andItemidLessThanOrEqualTo(Short value) {
            addCriterion("itemID <=", value, "itemid");
            return (Criteria) this;
        }

        public Criteria andItemidIn(List<Short> values) {
            addCriterion("itemID in", values, "itemid");
            return (Criteria) this;
        }

        public Criteria andItemidNotIn(List<Short> values) {
            addCriterion("itemID not in", values, "itemid");
            return (Criteria) this;
        }

        public Criteria andItemidBetween(Short value1, Short value2) {
            addCriterion("itemID between", value1, value2, "itemid");
            return (Criteria) this;
        }

        public Criteria andItemidNotBetween(Short value1, Short value2) {
            addCriterion("itemID not between", value1, value2, "itemid");
            return (Criteria) this;
        }

        public Criteria andItemcodeIsNull() {
            addCriterion("itemCode is null");
            return (Criteria) this;
        }

        public Criteria andItemcodeIsNotNull() {
            addCriterion("itemCode is not null");
            return (Criteria) this;
        }

        public Criteria andItemcodeEqualTo(String value) {
            addCriterion("itemCode =", value, "itemcode");
            return (Criteria) this;
        }

        public Criteria andItemcodeNotEqualTo(String value) {
            addCriterion("itemCode <>", value, "itemcode");
            return (Criteria) this;
        }

        public Criteria andItemcodeGreaterThan(String value) {
            addCriterion("itemCode >", value, "itemcode");
            return (Criteria) this;
        }

        public Criteria andItemcodeGreaterThanOrEqualTo(String value) {
            addCriterion("itemCode >=", value, "itemcode");
            return (Criteria) this;
        }

        public Criteria andItemcodeLessThan(String value) {
            addCriterion("itemCode <", value, "itemcode");
            return (Criteria) this;
        }

        public Criteria andItemcodeLessThanOrEqualTo(String value) {
            addCriterion("itemCode <=", value, "itemcode");
            return (Criteria) this;
        }

        public Criteria andItemcodeLike(String value) {
            addCriterion("itemCode like", value, "itemcode");
            return (Criteria) this;
        }

        public Criteria andItemcodeNotLike(String value) {
            addCriterion("itemCode not like", value, "itemcode");
            return (Criteria) this;
        }

        public Criteria andItemcodeIn(List<String> values) {
            addCriterion("itemCode in", values, "itemcode");
            return (Criteria) this;
        }

        public Criteria andItemcodeNotIn(List<String> values) {
            addCriterion("itemCode not in", values, "itemcode");
            return (Criteria) this;
        }

        public Criteria andItemcodeBetween(String value1, String value2) {
            addCriterion("itemCode between", value1, value2, "itemcode");
            return (Criteria) this;
        }

        public Criteria andItemcodeNotBetween(String value1, String value2) {
            addCriterion("itemCode not between", value1, value2, "itemcode");
            return (Criteria) this;
        }

        public Criteria andItemnameIsNull() {
            addCriterion("itemName is null");
            return (Criteria) this;
        }

        public Criteria andItemnameIsNotNull() {
            addCriterion("itemName is not null");
            return (Criteria) this;
        }

        public Criteria andItemnameEqualTo(String value) {
            addCriterion("itemName =", value, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameNotEqualTo(String value) {
            addCriterion("itemName <>", value, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameGreaterThan(String value) {
            addCriterion("itemName >", value, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameGreaterThanOrEqualTo(String value) {
            addCriterion("itemName >=", value, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameLessThan(String value) {
            addCriterion("itemName <", value, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameLessThanOrEqualTo(String value) {
            addCriterion("itemName <=", value, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameLike(String value) {
            addCriterion("itemName like", value, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameNotLike(String value) {
            addCriterion("itemName not like", value, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameIn(List<String> values) {
            addCriterion("itemName in", values, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameNotIn(List<String> values) {
            addCriterion("itemName not in", values, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameBetween(String value1, String value2) {
            addCriterion("itemName between", value1, value2, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameNotBetween(String value1, String value2) {
            addCriterion("itemName not between", value1, value2, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemspecifIsNull() {
            addCriterion("itemSpecif is null");
            return (Criteria) this;
        }

        public Criteria andItemspecifIsNotNull() {
            addCriterion("itemSpecif is not null");
            return (Criteria) this;
        }

        public Criteria andItemspecifEqualTo(String value) {
            addCriterion("itemSpecif =", value, "itemspecif");
            return (Criteria) this;
        }

        public Criteria andItemspecifNotEqualTo(String value) {
            addCriterion("itemSpecif <>", value, "itemspecif");
            return (Criteria) this;
        }

        public Criteria andItemspecifGreaterThan(String value) {
            addCriterion("itemSpecif >", value, "itemspecif");
            return (Criteria) this;
        }

        public Criteria andItemspecifGreaterThanOrEqualTo(String value) {
            addCriterion("itemSpecif >=", value, "itemspecif");
            return (Criteria) this;
        }

        public Criteria andItemspecifLessThan(String value) {
            addCriterion("itemSpecif <", value, "itemspecif");
            return (Criteria) this;
        }

        public Criteria andItemspecifLessThanOrEqualTo(String value) {
            addCriterion("itemSpecif <=", value, "itemspecif");
            return (Criteria) this;
        }

        public Criteria andItemspecifLike(String value) {
            addCriterion("itemSpecif like", value, "itemspecif");
            return (Criteria) this;
        }

        public Criteria andItemspecifNotLike(String value) {
            addCriterion("itemSpecif not like", value, "itemspecif");
            return (Criteria) this;
        }

        public Criteria andItemspecifIn(List<String> values) {
            addCriterion("itemSpecif in", values, "itemspecif");
            return (Criteria) this;
        }

        public Criteria andItemspecifNotIn(List<String> values) {
            addCriterion("itemSpecif not in", values, "itemspecif");
            return (Criteria) this;
        }

        public Criteria andItemspecifBetween(String value1, String value2) {
            addCriterion("itemSpecif between", value1, value2, "itemspecif");
            return (Criteria) this;
        }

        public Criteria andItemspecifNotBetween(String value1, String value2) {
            addCriterion("itemSpecif not between", value1, value2, "itemspecif");
            return (Criteria) this;
        }

        public Criteria andItempriceIsNull() {
            addCriterion("itemPrice is null");
            return (Criteria) this;
        }

        public Criteria andItempriceIsNotNull() {
            addCriterion("itemPrice is not null");
            return (Criteria) this;
        }

        public Criteria andItempriceEqualTo(Float value) {
            addCriterion("itemPrice =", value, "itemprice");
            return (Criteria) this;
        }

        public Criteria andItempriceNotEqualTo(Float value) {
            addCriterion("itemPrice <>", value, "itemprice");
            return (Criteria) this;
        }

        public Criteria andItempriceGreaterThan(Float value) {
            addCriterion("itemPrice >", value, "itemprice");
            return (Criteria) this;
        }

        public Criteria andItempriceGreaterThanOrEqualTo(Float value) {
            addCriterion("itemPrice >=", value, "itemprice");
            return (Criteria) this;
        }

        public Criteria andItempriceLessThan(Float value) {
            addCriterion("itemPrice <", value, "itemprice");
            return (Criteria) this;
        }

        public Criteria andItempriceLessThanOrEqualTo(Float value) {
            addCriterion("itemPrice <=", value, "itemprice");
            return (Criteria) this;
        }

        public Criteria andItempriceIn(List<Float> values) {
            addCriterion("itemPrice in", values, "itemprice");
            return (Criteria) this;
        }

        public Criteria andItempriceNotIn(List<Float> values) {
            addCriterion("itemPrice not in", values, "itemprice");
            return (Criteria) this;
        }

        public Criteria andItempriceBetween(Float value1, Float value2) {
            addCriterion("itemPrice between", value1, value2, "itemprice");
            return (Criteria) this;
        }

        public Criteria andItempriceNotBetween(Float value1, Float value2) {
            addCriterion("itemPrice not between", value1, value2, "itemprice");
            return (Criteria) this;
        }

        public Criteria andChargesubjectcodeIsNull() {
            addCriterion("chargeSubjectCode is null");
            return (Criteria) this;
        }

        public Criteria andChargesubjectcodeIsNotNull() {
            addCriterion("chargeSubjectCode is not null");
            return (Criteria) this;
        }

        public Criteria andChargesubjectcodeEqualTo(Byte value) {
            addCriterion("chargeSubjectCode =", value, "chargesubjectcode");
            return (Criteria) this;
        }

        public Criteria andChargesubjectcodeNotEqualTo(Byte value) {
            addCriterion("chargeSubjectCode <>", value, "chargesubjectcode");
            return (Criteria) this;
        }

        public Criteria andChargesubjectcodeGreaterThan(Byte value) {
            addCriterion("chargeSubjectCode >", value, "chargesubjectcode");
            return (Criteria) this;
        }

        public Criteria andChargesubjectcodeGreaterThanOrEqualTo(Byte value) {
            addCriterion("chargeSubjectCode >=", value, "chargesubjectcode");
            return (Criteria) this;
        }

        public Criteria andChargesubjectcodeLessThan(Byte value) {
            addCriterion("chargeSubjectCode <", value, "chargesubjectcode");
            return (Criteria) this;
        }

        public Criteria andChargesubjectcodeLessThanOrEqualTo(Byte value) {
            addCriterion("chargeSubjectCode <=", value, "chargesubjectcode");
            return (Criteria) this;
        }

        public Criteria andChargesubjectcodeIn(List<Byte> values) {
            addCriterion("chargeSubjectCode in", values, "chargesubjectcode");
            return (Criteria) this;
        }

        public Criteria andChargesubjectcodeNotIn(List<Byte> values) {
            addCriterion("chargeSubjectCode not in", values, "chargesubjectcode");
            return (Criteria) this;
        }

        public Criteria andChargesubjectcodeBetween(Byte value1, Byte value2) {
            addCriterion("chargeSubjectCode between", value1, value2, "chargesubjectcode");
            return (Criteria) this;
        }

        public Criteria andChargesubjectcodeNotBetween(Byte value1, Byte value2) {
            addCriterion("chargeSubjectCode not between", value1, value2, "chargesubjectcode");
            return (Criteria) this;
        }

        public Criteria andDeptidIsNull() {
            addCriterion("deptID is null");
            return (Criteria) this;
        }

        public Criteria andDeptidIsNotNull() {
            addCriterion("deptID is not null");
            return (Criteria) this;
        }

        public Criteria andDeptidEqualTo(Short value) {
            addCriterion("deptID =", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidNotEqualTo(Short value) {
            addCriterion("deptID <>", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidGreaterThan(Short value) {
            addCriterion("deptID >", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidGreaterThanOrEqualTo(Short value) {
            addCriterion("deptID >=", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidLessThan(Short value) {
            addCriterion("deptID <", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidLessThanOrEqualTo(Short value) {
            addCriterion("deptID <=", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidIn(List<Short> values) {
            addCriterion("deptID in", values, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidNotIn(List<Short> values) {
            addCriterion("deptID not in", values, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidBetween(Short value1, Short value2) {
            addCriterion("deptID between", value1, value2, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidNotBetween(Short value1, Short value2) {
            addCriterion("deptID not between", value1, value2, "deptid");
            return (Criteria) this;
        }

        public Criteria andItemtypeIsNull() {
            addCriterion("itemType is null");
            return (Criteria) this;
        }

        public Criteria andItemtypeIsNotNull() {
            addCriterion("itemType is not null");
            return (Criteria) this;
        }

        public Criteria andItemtypeEqualTo(Boolean value) {
            addCriterion("itemType =", value, "itemtype");
            return (Criteria) this;
        }

        public Criteria andItemtypeNotEqualTo(Boolean value) {
            addCriterion("itemType <>", value, "itemtype");
            return (Criteria) this;
        }

        public Criteria andItemtypeGreaterThan(Boolean value) {
            addCriterion("itemType >", value, "itemtype");
            return (Criteria) this;
        }

        public Criteria andItemtypeGreaterThanOrEqualTo(Boolean value) {
            addCriterion("itemType >=", value, "itemtype");
            return (Criteria) this;
        }

        public Criteria andItemtypeLessThan(Boolean value) {
            addCriterion("itemType <", value, "itemtype");
            return (Criteria) this;
        }

        public Criteria andItemtypeLessThanOrEqualTo(Boolean value) {
            addCriterion("itemType <=", value, "itemtype");
            return (Criteria) this;
        }

        public Criteria andItemtypeIn(List<Boolean> values) {
            addCriterion("itemType in", values, "itemtype");
            return (Criteria) this;
        }

        public Criteria andItemtypeNotIn(List<Boolean> values) {
            addCriterion("itemType not in", values, "itemtype");
            return (Criteria) this;
        }

        public Criteria andItemtypeBetween(Boolean value1, Boolean value2) {
            addCriterion("itemType between", value1, value2, "itemtype");
            return (Criteria) this;
        }

        public Criteria andItemtypeNotBetween(Boolean value1, Boolean value2) {
            addCriterion("itemType not between", value1, value2, "itemtype");
            return (Criteria) this;
        }

        public Criteria andItemcrttimeIsNull() {
            addCriterion("itemCrtTime is null");
            return (Criteria) this;
        }

        public Criteria andItemcrttimeIsNotNull() {
            addCriterion("itemCrtTime is not null");
            return (Criteria) this;
        }

        public Criteria andItemcrttimeEqualTo(Date value) {
            addCriterionForJDBCDate("itemCrtTime =", value, "itemcrttime");
            return (Criteria) this;
        }

        public Criteria andItemcrttimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("itemCrtTime <>", value, "itemcrttime");
            return (Criteria) this;
        }

        public Criteria andItemcrttimeGreaterThan(Date value) {
            addCriterionForJDBCDate("itemCrtTime >", value, "itemcrttime");
            return (Criteria) this;
        }

        public Criteria andItemcrttimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("itemCrtTime >=", value, "itemcrttime");
            return (Criteria) this;
        }

        public Criteria andItemcrttimeLessThan(Date value) {
            addCriterionForJDBCDate("itemCrtTime <", value, "itemcrttime");
            return (Criteria) this;
        }

        public Criteria andItemcrttimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("itemCrtTime <=", value, "itemcrttime");
            return (Criteria) this;
        }

        public Criteria andItemcrttimeIn(List<Date> values) {
            addCriterionForJDBCDate("itemCrtTime in", values, "itemcrttime");
            return (Criteria) this;
        }

        public Criteria andItemcrttimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("itemCrtTime not in", values, "itemcrttime");
            return (Criteria) this;
        }

        public Criteria andItemcrttimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("itemCrtTime between", value1, value2, "itemcrttime");
            return (Criteria) this;
        }

        public Criteria andItemcrttimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("itemCrtTime not between", value1, value2, "itemcrttime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table non_drug_item
     *
     * @mbg.generated do_not_delete_during_merge Mon Jul 22 15:20:08 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table non_drug_item
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}