package com.neu.his.model;

public class RegistLevel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column regist_level.registLevelID
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    private Boolean registlevelid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column regist_level.registLevelCode
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    private String registlevelcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column regist_level.registLevelName
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    private String registlevelname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column regist_level.registLevelSeq
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    private String registlevelseq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column regist_level.registLevelPrice
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    private Byte registlevelprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column regist_level.registLevelLimit
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    private Byte registlevellimit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column regist_level.registLevelID
     *
     * @return the value of regist_level.registLevelID
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public Boolean getRegistlevelid() {
        return registlevelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column regist_level.registLevelID
     *
     * @param registlevelid the value for regist_level.registLevelID
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public void setRegistlevelid(Boolean registlevelid) {
        this.registlevelid = registlevelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column regist_level.registLevelCode
     *
     * @return the value of regist_level.registLevelCode
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public String getRegistlevelcode() {
        return registlevelcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column regist_level.registLevelCode
     *
     * @param registlevelcode the value for regist_level.registLevelCode
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public void setRegistlevelcode(String registlevelcode) {
        this.registlevelcode = registlevelcode == null ? null : registlevelcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column regist_level.registLevelName
     *
     * @return the value of regist_level.registLevelName
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public String getRegistlevelname() {
        return registlevelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column regist_level.registLevelName
     *
     * @param registlevelname the value for regist_level.registLevelName
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public void setRegistlevelname(String registlevelname) {
        this.registlevelname = registlevelname == null ? null : registlevelname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column regist_level.registLevelSeq
     *
     * @return the value of regist_level.registLevelSeq
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public String getRegistlevelseq() {
        return registlevelseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column regist_level.registLevelSeq
     *
     * @param registlevelseq the value for regist_level.registLevelSeq
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public void setRegistlevelseq(String registlevelseq) {
        this.registlevelseq = registlevelseq == null ? null : registlevelseq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column regist_level.registLevelPrice
     *
     * @return the value of regist_level.registLevelPrice
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public Byte getRegistlevelprice() {
        return registlevelprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column regist_level.registLevelPrice
     *
     * @param registlevelprice the value for regist_level.registLevelPrice
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public void setRegistlevelprice(Byte registlevelprice) {
        this.registlevelprice = registlevelprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column regist_level.registLevelLimit
     *
     * @return the value of regist_level.registLevelLimit
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public Byte getRegistlevellimit() {
        return registlevellimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column regist_level.registLevelLimit
     *
     * @param registlevellimit the value for regist_level.registLevelLimit
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public void setRegistlevellimit(Byte registlevellimit) {
        this.registlevellimit = registlevellimit;
    }
}