package com.neu.his.model;

import java.util.Date;

public class Scheduling {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scheduling.scheID
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    private Integer scheid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scheduling.doctorID
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    private Short doctorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scheduling.scheTime
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    private Date schetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scheduling.scheNoon
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    private String schenoon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scheduling.scheRuleID
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    private Byte scheruleid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduling.scheID
     *
     * @return the value of scheduling.scheID
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public Integer getScheid() {
        return scheid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduling.scheID
     *
     * @param scheid the value for scheduling.scheID
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public void setScheid(Integer scheid) {
        this.scheid = scheid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduling.doctorID
     *
     * @return the value of scheduling.doctorID
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public Short getDoctorid() {
        return doctorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduling.doctorID
     *
     * @param doctorid the value for scheduling.doctorID
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public void setDoctorid(Short doctorid) {
        this.doctorid = doctorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduling.scheTime
     *
     * @return the value of scheduling.scheTime
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public Date getSchetime() {
        return schetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduling.scheTime
     *
     * @param schetime the value for scheduling.scheTime
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public void setSchetime(Date schetime) {
        this.schetime = schetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduling.scheNoon
     *
     * @return the value of scheduling.scheNoon
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public String getSchenoon() {
        return schenoon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduling.scheNoon
     *
     * @param schenoon the value for scheduling.scheNoon
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public void setSchenoon(String schenoon) {
        this.schenoon = schenoon == null ? null : schenoon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scheduling.scheRuleID
     *
     * @return the value of scheduling.scheRuleID
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public Byte getScheruleid() {
        return scheruleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scheduling.scheRuleID
     *
     * @param scheruleid the value for scheduling.scheRuleID
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public void setScheruleid(Byte scheruleid) {
        this.scheruleid = scheruleid;
    }
}