package com.neu.his.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SettlementExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table settlement
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table settlement
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table settlement
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlement
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public SettlementExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlement
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlement
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlement
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlement
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlement
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlement
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlement
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlement
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlement
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settlement
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table settlement
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSettlementidIsNull() {
            addCriterion("settlementID is null");
            return (Criteria) this;
        }

        public Criteria andSettlementidIsNotNull() {
            addCriterion("settlementID is not null");
            return (Criteria) this;
        }

        public Criteria andSettlementidEqualTo(Integer value) {
            addCriterion("settlementID =", value, "settlementid");
            return (Criteria) this;
        }

        public Criteria andSettlementidNotEqualTo(Integer value) {
            addCriterion("settlementID <>", value, "settlementid");
            return (Criteria) this;
        }

        public Criteria andSettlementidGreaterThan(Integer value) {
            addCriterion("settlementID >", value, "settlementid");
            return (Criteria) this;
        }

        public Criteria andSettlementidGreaterThanOrEqualTo(Integer value) {
            addCriterion("settlementID >=", value, "settlementid");
            return (Criteria) this;
        }

        public Criteria andSettlementidLessThan(Integer value) {
            addCriterion("settlementID <", value, "settlementid");
            return (Criteria) this;
        }

        public Criteria andSettlementidLessThanOrEqualTo(Integer value) {
            addCriterion("settlementID <=", value, "settlementid");
            return (Criteria) this;
        }

        public Criteria andSettlementidIn(List<Integer> values) {
            addCriterion("settlementID in", values, "settlementid");
            return (Criteria) this;
        }

        public Criteria andSettlementidNotIn(List<Integer> values) {
            addCriterion("settlementID not in", values, "settlementid");
            return (Criteria) this;
        }

        public Criteria andSettlementidBetween(Integer value1, Integer value2) {
            addCriterion("settlementID between", value1, value2, "settlementid");
            return (Criteria) this;
        }

        public Criteria andSettlementidNotBetween(Integer value1, Integer value2) {
            addCriterion("settlementID not between", value1, value2, "settlementid");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("userID is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("userID is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(Short value) {
            addCriterion("userID =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(Short value) {
            addCriterion("userID <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(Short value) {
            addCriterion("userID >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(Short value) {
            addCriterion("userID >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(Short value) {
            addCriterion("userID <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(Short value) {
            addCriterion("userID <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<Short> values) {
            addCriterion("userID in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<Short> values) {
            addCriterion("userID not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(Short value1, Short value2) {
            addCriterion("userID between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(Short value1, Short value2) {
            addCriterion("userID not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andSettlementstarttimeIsNull() {
            addCriterion("settlementStartTime is null");
            return (Criteria) this;
        }

        public Criteria andSettlementstarttimeIsNotNull() {
            addCriterion("settlementStartTime is not null");
            return (Criteria) this;
        }

        public Criteria andSettlementstarttimeEqualTo(Date value) {
            addCriterion("settlementStartTime =", value, "settlementstarttime");
            return (Criteria) this;
        }

        public Criteria andSettlementstarttimeNotEqualTo(Date value) {
            addCriterion("settlementStartTime <>", value, "settlementstarttime");
            return (Criteria) this;
        }

        public Criteria andSettlementstarttimeGreaterThan(Date value) {
            addCriterion("settlementStartTime >", value, "settlementstarttime");
            return (Criteria) this;
        }

        public Criteria andSettlementstarttimeGreaterThanOrEqualTo(Date value) {
            addCriterion("settlementStartTime >=", value, "settlementstarttime");
            return (Criteria) this;
        }

        public Criteria andSettlementstarttimeLessThan(Date value) {
            addCriterion("settlementStartTime <", value, "settlementstarttime");
            return (Criteria) this;
        }

        public Criteria andSettlementstarttimeLessThanOrEqualTo(Date value) {
            addCriterion("settlementStartTime <=", value, "settlementstarttime");
            return (Criteria) this;
        }

        public Criteria andSettlementstarttimeIn(List<Date> values) {
            addCriterion("settlementStartTime in", values, "settlementstarttime");
            return (Criteria) this;
        }

        public Criteria andSettlementstarttimeNotIn(List<Date> values) {
            addCriterion("settlementStartTime not in", values, "settlementstarttime");
            return (Criteria) this;
        }

        public Criteria andSettlementstarttimeBetween(Date value1, Date value2) {
            addCriterion("settlementStartTime between", value1, value2, "settlementstarttime");
            return (Criteria) this;
        }

        public Criteria andSettlementstarttimeNotBetween(Date value1, Date value2) {
            addCriterion("settlementStartTime not between", value1, value2, "settlementstarttime");
            return (Criteria) this;
        }

        public Criteria andSettlementendtimeIsNull() {
            addCriterion("settlementEndTime is null");
            return (Criteria) this;
        }

        public Criteria andSettlementendtimeIsNotNull() {
            addCriterion("settlementEndTime is not null");
            return (Criteria) this;
        }

        public Criteria andSettlementendtimeEqualTo(Date value) {
            addCriterion("settlementEndTime =", value, "settlementendtime");
            return (Criteria) this;
        }

        public Criteria andSettlementendtimeNotEqualTo(Date value) {
            addCriterion("settlementEndTime <>", value, "settlementendtime");
            return (Criteria) this;
        }

        public Criteria andSettlementendtimeGreaterThan(Date value) {
            addCriterion("settlementEndTime >", value, "settlementendtime");
            return (Criteria) this;
        }

        public Criteria andSettlementendtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("settlementEndTime >=", value, "settlementendtime");
            return (Criteria) this;
        }

        public Criteria andSettlementendtimeLessThan(Date value) {
            addCriterion("settlementEndTime <", value, "settlementendtime");
            return (Criteria) this;
        }

        public Criteria andSettlementendtimeLessThanOrEqualTo(Date value) {
            addCriterion("settlementEndTime <=", value, "settlementendtime");
            return (Criteria) this;
        }

        public Criteria andSettlementendtimeIn(List<Date> values) {
            addCriterion("settlementEndTime in", values, "settlementendtime");
            return (Criteria) this;
        }

        public Criteria andSettlementendtimeNotIn(List<Date> values) {
            addCriterion("settlementEndTime not in", values, "settlementendtime");
            return (Criteria) this;
        }

        public Criteria andSettlementendtimeBetween(Date value1, Date value2) {
            addCriterion("settlementEndTime between", value1, value2, "settlementendtime");
            return (Criteria) this;
        }

        public Criteria andSettlementendtimeNotBetween(Date value1, Date value2) {
            addCriterion("settlementEndTime not between", value1, value2, "settlementendtime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table settlement
     *
     * @mbg.generated do_not_delete_during_merge Mon Jul 22 15:20:08 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table settlement
     *
     * @mbg.generated Mon Jul 22 15:20:08 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}