package com.neu.his.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ChargeInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table charge_info
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table charge_info
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table charge_info
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_info
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    public ChargeInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_info
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_info
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_info
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_info
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_info
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_info
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_info
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_info
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_info
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_info
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table charge_info
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andChargeInforIdIsNull() {
            addCriterion("charge_infor_id is null");
            return (Criteria) this;
        }

        public Criteria andChargeInforIdIsNotNull() {
            addCriterion("charge_infor_id is not null");
            return (Criteria) this;
        }

        public Criteria andChargeInforIdEqualTo(Integer value) {
            addCriterion("charge_infor_id =", value, "chargeInforId");
            return (Criteria) this;
        }

        public Criteria andChargeInforIdNotEqualTo(Integer value) {
            addCriterion("charge_infor_id <>", value, "chargeInforId");
            return (Criteria) this;
        }

        public Criteria andChargeInforIdGreaterThan(Integer value) {
            addCriterion("charge_infor_id >", value, "chargeInforId");
            return (Criteria) this;
        }

        public Criteria andChargeInforIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("charge_infor_id >=", value, "chargeInforId");
            return (Criteria) this;
        }

        public Criteria andChargeInforIdLessThan(Integer value) {
            addCriterion("charge_infor_id <", value, "chargeInforId");
            return (Criteria) this;
        }

        public Criteria andChargeInforIdLessThanOrEqualTo(Integer value) {
            addCriterion("charge_infor_id <=", value, "chargeInforId");
            return (Criteria) this;
        }

        public Criteria andChargeInforIdIn(List<Integer> values) {
            addCriterion("charge_infor_id in", values, "chargeInforId");
            return (Criteria) this;
        }

        public Criteria andChargeInforIdNotIn(List<Integer> values) {
            addCriterion("charge_infor_id not in", values, "chargeInforId");
            return (Criteria) this;
        }

        public Criteria andChargeInforIdBetween(Integer value1, Integer value2) {
            addCriterion("charge_infor_id between", value1, value2, "chargeInforId");
            return (Criteria) this;
        }

        public Criteria andChargeInforIdNotBetween(Integer value1, Integer value2) {
            addCriterion("charge_infor_id not between", value1, value2, "chargeInforId");
            return (Criteria) this;
        }

        public Criteria andRegistIdIsNull() {
            addCriterion("regist_id is null");
            return (Criteria) this;
        }

        public Criteria andRegistIdIsNotNull() {
            addCriterion("regist_id is not null");
            return (Criteria) this;
        }

        public Criteria andRegistIdEqualTo(Integer value) {
            addCriterion("regist_id =", value, "registId");
            return (Criteria) this;
        }

        public Criteria andRegistIdNotEqualTo(Integer value) {
            addCriterion("regist_id <>", value, "registId");
            return (Criteria) this;
        }

        public Criteria andRegistIdGreaterThan(Integer value) {
            addCriterion("regist_id >", value, "registId");
            return (Criteria) this;
        }

        public Criteria andRegistIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("regist_id >=", value, "registId");
            return (Criteria) this;
        }

        public Criteria andRegistIdLessThan(Integer value) {
            addCriterion("regist_id <", value, "registId");
            return (Criteria) this;
        }

        public Criteria andRegistIdLessThanOrEqualTo(Integer value) {
            addCriterion("regist_id <=", value, "registId");
            return (Criteria) this;
        }

        public Criteria andRegistIdIn(List<Integer> values) {
            addCriterion("regist_id in", values, "registId");
            return (Criteria) this;
        }

        public Criteria andRegistIdNotIn(List<Integer> values) {
            addCriterion("regist_id not in", values, "registId");
            return (Criteria) this;
        }

        public Criteria andRegistIdBetween(Integer value1, Integer value2) {
            addCriterion("regist_id between", value1, value2, "registId");
            return (Criteria) this;
        }

        public Criteria andRegistIdNotBetween(Integer value1, Integer value2) {
            addCriterion("regist_id not between", value1, value2, "registId");
            return (Criteria) this;
        }

        public Criteria andInvoiceIdIsNull() {
            addCriterion("invoice_id is null");
            return (Criteria) this;
        }

        public Criteria andInvoiceIdIsNotNull() {
            addCriterion("invoice_id is not null");
            return (Criteria) this;
        }

        public Criteria andInvoiceIdEqualTo(Integer value) {
            addCriterion("invoice_id =", value, "invoiceId");
            return (Criteria) this;
        }

        public Criteria andInvoiceIdNotEqualTo(Integer value) {
            addCriterion("invoice_id <>", value, "invoiceId");
            return (Criteria) this;
        }

        public Criteria andInvoiceIdGreaterThan(Integer value) {
            addCriterion("invoice_id >", value, "invoiceId");
            return (Criteria) this;
        }

        public Criteria andInvoiceIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("invoice_id >=", value, "invoiceId");
            return (Criteria) this;
        }

        public Criteria andInvoiceIdLessThan(Integer value) {
            addCriterion("invoice_id <", value, "invoiceId");
            return (Criteria) this;
        }

        public Criteria andInvoiceIdLessThanOrEqualTo(Integer value) {
            addCriterion("invoice_id <=", value, "invoiceId");
            return (Criteria) this;
        }

        public Criteria andInvoiceIdIn(List<Integer> values) {
            addCriterion("invoice_id in", values, "invoiceId");
            return (Criteria) this;
        }

        public Criteria andInvoiceIdNotIn(List<Integer> values) {
            addCriterion("invoice_id not in", values, "invoiceId");
            return (Criteria) this;
        }

        public Criteria andInvoiceIdBetween(Integer value1, Integer value2) {
            addCriterion("invoice_id between", value1, value2, "invoiceId");
            return (Criteria) this;
        }

        public Criteria andInvoiceIdNotBetween(Integer value1, Integer value2) {
            addCriterion("invoice_id not between", value1, value2, "invoiceId");
            return (Criteria) this;
        }

        public Criteria andItemIdIsNull() {
            addCriterion("item_id is null");
            return (Criteria) this;
        }

        public Criteria andItemIdIsNotNull() {
            addCriterion("item_id is not null");
            return (Criteria) this;
        }

        public Criteria andItemIdEqualTo(Short value) {
            addCriterion("item_id =", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotEqualTo(Short value) {
            addCriterion("item_id <>", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdGreaterThan(Short value) {
            addCriterion("item_id >", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdGreaterThanOrEqualTo(Short value) {
            addCriterion("item_id >=", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLessThan(Short value) {
            addCriterion("item_id <", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLessThanOrEqualTo(Short value) {
            addCriterion("item_id <=", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdIn(List<Short> values) {
            addCriterion("item_id in", values, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotIn(List<Short> values) {
            addCriterion("item_id not in", values, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdBetween(Short value1, Short value2) {
            addCriterion("item_id between", value1, value2, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotBetween(Short value1, Short value2) {
            addCriterion("item_id not between", value1, value2, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemTypeIsNull() {
            addCriterion("item_type is null");
            return (Criteria) this;
        }

        public Criteria andItemTypeIsNotNull() {
            addCriterion("item_type is not null");
            return (Criteria) this;
        }

        public Criteria andItemTypeEqualTo(Boolean value) {
            addCriterion("item_type =", value, "itemType");
            return (Criteria) this;
        }

        public Criteria andItemTypeNotEqualTo(Boolean value) {
            addCriterion("item_type <>", value, "itemType");
            return (Criteria) this;
        }

        public Criteria andItemTypeGreaterThan(Boolean value) {
            addCriterion("item_type >", value, "itemType");
            return (Criteria) this;
        }

        public Criteria andItemTypeGreaterThanOrEqualTo(Boolean value) {
            addCriterion("item_type >=", value, "itemType");
            return (Criteria) this;
        }

        public Criteria andItemTypeLessThan(Boolean value) {
            addCriterion("item_type <", value, "itemType");
            return (Criteria) this;
        }

        public Criteria andItemTypeLessThanOrEqualTo(Boolean value) {
            addCriterion("item_type <=", value, "itemType");
            return (Criteria) this;
        }

        public Criteria andItemTypeIn(List<Boolean> values) {
            addCriterion("item_type in", values, "itemType");
            return (Criteria) this;
        }

        public Criteria andItemTypeNotIn(List<Boolean> values) {
            addCriterion("item_type not in", values, "itemType");
            return (Criteria) this;
        }

        public Criteria andItemTypeBetween(Boolean value1, Boolean value2) {
            addCriterion("item_type between", value1, value2, "itemType");
            return (Criteria) this;
        }

        public Criteria andItemTypeNotBetween(Boolean value1, Boolean value2) {
            addCriterion("item_type not between", value1, value2, "itemType");
            return (Criteria) this;
        }

        public Criteria andItemNameIsNull() {
            addCriterion("item_name is null");
            return (Criteria) this;
        }

        public Criteria andItemNameIsNotNull() {
            addCriterion("item_name is not null");
            return (Criteria) this;
        }

        public Criteria andItemNameEqualTo(String value) {
            addCriterion("item_name =", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameNotEqualTo(String value) {
            addCriterion("item_name <>", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameGreaterThan(String value) {
            addCriterion("item_name >", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameGreaterThanOrEqualTo(String value) {
            addCriterion("item_name >=", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameLessThan(String value) {
            addCriterion("item_name <", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameLessThanOrEqualTo(String value) {
            addCriterion("item_name <=", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameLike(String value) {
            addCriterion("item_name like", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameNotLike(String value) {
            addCriterion("item_name not like", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameIn(List<String> values) {
            addCriterion("item_name in", values, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameNotIn(List<String> values) {
            addCriterion("item_name not in", values, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameBetween(String value1, String value2) {
            addCriterion("item_name between", value1, value2, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameNotBetween(String value1, String value2) {
            addCriterion("item_name not between", value1, value2, "itemName");
            return (Criteria) this;
        }

        public Criteria andChargeInfoUnitPriceIsNull() {
            addCriterion("charge_info_unit_price is null");
            return (Criteria) this;
        }

        public Criteria andChargeInfoUnitPriceIsNotNull() {
            addCriterion("charge_info_unit_price is not null");
            return (Criteria) this;
        }

        public Criteria andChargeInfoUnitPriceEqualTo(Double value) {
            addCriterion("charge_info_unit_price =", value, "chargeInfoUnitPrice");
            return (Criteria) this;
        }

        public Criteria andChargeInfoUnitPriceNotEqualTo(Double value) {
            addCriterion("charge_info_unit_price <>", value, "chargeInfoUnitPrice");
            return (Criteria) this;
        }

        public Criteria andChargeInfoUnitPriceGreaterThan(Double value) {
            addCriterion("charge_info_unit_price >", value, "chargeInfoUnitPrice");
            return (Criteria) this;
        }

        public Criteria andChargeInfoUnitPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("charge_info_unit_price >=", value, "chargeInfoUnitPrice");
            return (Criteria) this;
        }

        public Criteria andChargeInfoUnitPriceLessThan(Double value) {
            addCriterion("charge_info_unit_price <", value, "chargeInfoUnitPrice");
            return (Criteria) this;
        }

        public Criteria andChargeInfoUnitPriceLessThanOrEqualTo(Double value) {
            addCriterion("charge_info_unit_price <=", value, "chargeInfoUnitPrice");
            return (Criteria) this;
        }

        public Criteria andChargeInfoUnitPriceIn(List<Double> values) {
            addCriterion("charge_info_unit_price in", values, "chargeInfoUnitPrice");
            return (Criteria) this;
        }

        public Criteria andChargeInfoUnitPriceNotIn(List<Double> values) {
            addCriterion("charge_info_unit_price not in", values, "chargeInfoUnitPrice");
            return (Criteria) this;
        }

        public Criteria andChargeInfoUnitPriceBetween(Double value1, Double value2) {
            addCriterion("charge_info_unit_price between", value1, value2, "chargeInfoUnitPrice");
            return (Criteria) this;
        }

        public Criteria andChargeInfoUnitPriceNotBetween(Double value1, Double value2) {
            addCriterion("charge_info_unit_price not between", value1, value2, "chargeInfoUnitPrice");
            return (Criteria) this;
        }

        public Criteria andChargeInfoAmountIsNull() {
            addCriterion("charge_info_amount is null");
            return (Criteria) this;
        }

        public Criteria andChargeInfoAmountIsNotNull() {
            addCriterion("charge_info_amount is not null");
            return (Criteria) this;
        }

        public Criteria andChargeInfoAmountEqualTo(Short value) {
            addCriterion("charge_info_amount =", value, "chargeInfoAmount");
            return (Criteria) this;
        }

        public Criteria andChargeInfoAmountNotEqualTo(Short value) {
            addCriterion("charge_info_amount <>", value, "chargeInfoAmount");
            return (Criteria) this;
        }

        public Criteria andChargeInfoAmountGreaterThan(Short value) {
            addCriterion("charge_info_amount >", value, "chargeInfoAmount");
            return (Criteria) this;
        }

        public Criteria andChargeInfoAmountGreaterThanOrEqualTo(Short value) {
            addCriterion("charge_info_amount >=", value, "chargeInfoAmount");
            return (Criteria) this;
        }

        public Criteria andChargeInfoAmountLessThan(Short value) {
            addCriterion("charge_info_amount <", value, "chargeInfoAmount");
            return (Criteria) this;
        }

        public Criteria andChargeInfoAmountLessThanOrEqualTo(Short value) {
            addCriterion("charge_info_amount <=", value, "chargeInfoAmount");
            return (Criteria) this;
        }

        public Criteria andChargeInfoAmountIn(List<Short> values) {
            addCriterion("charge_info_amount in", values, "chargeInfoAmount");
            return (Criteria) this;
        }

        public Criteria andChargeInfoAmountNotIn(List<Short> values) {
            addCriterion("charge_info_amount not in", values, "chargeInfoAmount");
            return (Criteria) this;
        }

        public Criteria andChargeInfoAmountBetween(Short value1, Short value2) {
            addCriterion("charge_info_amount between", value1, value2, "chargeInfoAmount");
            return (Criteria) this;
        }

        public Criteria andChargeInfoAmountNotBetween(Short value1, Short value2) {
            addCriterion("charge_info_amount not between", value1, value2, "chargeInfoAmount");
            return (Criteria) this;
        }

        public Criteria andDeptIdIsNull() {
            addCriterion("dept_id is null");
            return (Criteria) this;
        }

        public Criteria andDeptIdIsNotNull() {
            addCriterion("dept_id is not null");
            return (Criteria) this;
        }

        public Criteria andDeptIdEqualTo(Short value) {
            addCriterion("dept_id =", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotEqualTo(Short value) {
            addCriterion("dept_id <>", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdGreaterThan(Short value) {
            addCriterion("dept_id >", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdGreaterThanOrEqualTo(Short value) {
            addCriterion("dept_id >=", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdLessThan(Short value) {
            addCriterion("dept_id <", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdLessThanOrEqualTo(Short value) {
            addCriterion("dept_id <=", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdIn(List<Short> values) {
            addCriterion("dept_id in", values, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotIn(List<Short> values) {
            addCriterion("dept_id not in", values, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdBetween(Short value1, Short value2) {
            addCriterion("dept_id between", value1, value2, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotBetween(Short value1, Short value2) {
            addCriterion("dept_id not between", value1, value2, "deptId");
            return (Criteria) this;
        }

        public Criteria andChargeRefundTimeIsNull() {
            addCriterion("charge_refund_time is null");
            return (Criteria) this;
        }

        public Criteria andChargeRefundTimeIsNotNull() {
            addCriterion("charge_refund_time is not null");
            return (Criteria) this;
        }

        public Criteria andChargeRefundTimeEqualTo(Date value) {
            addCriterion("charge_refund_time =", value, "chargeRefundTime");
            return (Criteria) this;
        }

        public Criteria andChargeRefundTimeNotEqualTo(Date value) {
            addCriterion("charge_refund_time <>", value, "chargeRefundTime");
            return (Criteria) this;
        }

        public Criteria andChargeRefundTimeGreaterThan(Date value) {
            addCriterion("charge_refund_time >", value, "chargeRefundTime");
            return (Criteria) this;
        }

        public Criteria andChargeRefundTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("charge_refund_time >=", value, "chargeRefundTime");
            return (Criteria) this;
        }

        public Criteria andChargeRefundTimeLessThan(Date value) {
            addCriterion("charge_refund_time <", value, "chargeRefundTime");
            return (Criteria) this;
        }

        public Criteria andChargeRefundTimeLessThanOrEqualTo(Date value) {
            addCriterion("charge_refund_time <=", value, "chargeRefundTime");
            return (Criteria) this;
        }

        public Criteria andChargeRefundTimeIn(List<Date> values) {
            addCriterion("charge_refund_time in", values, "chargeRefundTime");
            return (Criteria) this;
        }

        public Criteria andChargeRefundTimeNotIn(List<Date> values) {
            addCriterion("charge_refund_time not in", values, "chargeRefundTime");
            return (Criteria) this;
        }

        public Criteria andChargeRefundTimeBetween(Date value1, Date value2) {
            addCriterion("charge_refund_time between", value1, value2, "chargeRefundTime");
            return (Criteria) this;
        }

        public Criteria andChargeRefundTimeNotBetween(Date value1, Date value2) {
            addCriterion("charge_refund_time not between", value1, value2, "chargeRefundTime");
            return (Criteria) this;
        }

        public Criteria andChargeRefundUserIdIsNull() {
            addCriterion("charge_refund_user_id is null");
            return (Criteria) this;
        }

        public Criteria andChargeRefundUserIdIsNotNull() {
            addCriterion("charge_refund_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andChargeRefundUserIdEqualTo(Short value) {
            addCriterion("charge_refund_user_id =", value, "chargeRefundUserId");
            return (Criteria) this;
        }

        public Criteria andChargeRefundUserIdNotEqualTo(Short value) {
            addCriterion("charge_refund_user_id <>", value, "chargeRefundUserId");
            return (Criteria) this;
        }

        public Criteria andChargeRefundUserIdGreaterThan(Short value) {
            addCriterion("charge_refund_user_id >", value, "chargeRefundUserId");
            return (Criteria) this;
        }

        public Criteria andChargeRefundUserIdGreaterThanOrEqualTo(Short value) {
            addCriterion("charge_refund_user_id >=", value, "chargeRefundUserId");
            return (Criteria) this;
        }

        public Criteria andChargeRefundUserIdLessThan(Short value) {
            addCriterion("charge_refund_user_id <", value, "chargeRefundUserId");
            return (Criteria) this;
        }

        public Criteria andChargeRefundUserIdLessThanOrEqualTo(Short value) {
            addCriterion("charge_refund_user_id <=", value, "chargeRefundUserId");
            return (Criteria) this;
        }

        public Criteria andChargeRefundUserIdIn(List<Short> values) {
            addCriterion("charge_refund_user_id in", values, "chargeRefundUserId");
            return (Criteria) this;
        }

        public Criteria andChargeRefundUserIdNotIn(List<Short> values) {
            addCriterion("charge_refund_user_id not in", values, "chargeRefundUserId");
            return (Criteria) this;
        }

        public Criteria andChargeRefundUserIdBetween(Short value1, Short value2) {
            addCriterion("charge_refund_user_id between", value1, value2, "chargeRefundUserId");
            return (Criteria) this;
        }

        public Criteria andChargeRefundUserIdNotBetween(Short value1, Short value2) {
            addCriterion("charge_refund_user_id not between", value1, value2, "chargeRefundUserId");
            return (Criteria) this;
        }

        public Criteria andChargebegintimeIsNull() {
            addCriterion("chargeBeginTime is null");
            return (Criteria) this;
        }

        public Criteria andChargebegintimeIsNotNull() {
            addCriterion("chargeBeginTime is not null");
            return (Criteria) this;
        }

        public Criteria andChargebegintimeEqualTo(Date value) {
            addCriterion("chargeBeginTime =", value, "chargebegintime");
            return (Criteria) this;
        }

        public Criteria andChargebegintimeNotEqualTo(Date value) {
            addCriterion("chargeBeginTime <>", value, "chargebegintime");
            return (Criteria) this;
        }

        public Criteria andChargebegintimeGreaterThan(Date value) {
            addCriterion("chargeBeginTime >", value, "chargebegintime");
            return (Criteria) this;
        }

        public Criteria andChargebegintimeGreaterThanOrEqualTo(Date value) {
            addCriterion("chargeBeginTime >=", value, "chargebegintime");
            return (Criteria) this;
        }

        public Criteria andChargebegintimeLessThan(Date value) {
            addCriterion("chargeBeginTime <", value, "chargebegintime");
            return (Criteria) this;
        }

        public Criteria andChargebegintimeLessThanOrEqualTo(Date value) {
            addCriterion("chargeBeginTime <=", value, "chargebegintime");
            return (Criteria) this;
        }

        public Criteria andChargebegintimeIn(List<Date> values) {
            addCriterion("chargeBeginTime in", values, "chargebegintime");
            return (Criteria) this;
        }

        public Criteria andChargebegintimeNotIn(List<Date> values) {
            addCriterion("chargeBeginTime not in", values, "chargebegintime");
            return (Criteria) this;
        }

        public Criteria andChargebegintimeBetween(Date value1, Date value2) {
            addCriterion("chargeBeginTime between", value1, value2, "chargebegintime");
            return (Criteria) this;
        }

        public Criteria andChargebegintimeNotBetween(Date value1, Date value2) {
            addCriterion("chargeBeginTime not between", value1, value2, "chargebegintime");
            return (Criteria) this;
        }

        public Criteria andChargebeginuseridIsNull() {
            addCriterion("chargeBeginUserID is null");
            return (Criteria) this;
        }

        public Criteria andChargebeginuseridIsNotNull() {
            addCriterion("chargeBeginUserID is not null");
            return (Criteria) this;
        }

        public Criteria andChargebeginuseridEqualTo(Short value) {
            addCriterion("chargeBeginUserID =", value, "chargebeginuserid");
            return (Criteria) this;
        }

        public Criteria andChargebeginuseridNotEqualTo(Short value) {
            addCriterion("chargeBeginUserID <>", value, "chargebeginuserid");
            return (Criteria) this;
        }

        public Criteria andChargebeginuseridGreaterThan(Short value) {
            addCriterion("chargeBeginUserID >", value, "chargebeginuserid");
            return (Criteria) this;
        }

        public Criteria andChargebeginuseridGreaterThanOrEqualTo(Short value) {
            addCriterion("chargeBeginUserID >=", value, "chargebeginuserid");
            return (Criteria) this;
        }

        public Criteria andChargebeginuseridLessThan(Short value) {
            addCriterion("chargeBeginUserID <", value, "chargebeginuserid");
            return (Criteria) this;
        }

        public Criteria andChargebeginuseridLessThanOrEqualTo(Short value) {
            addCriterion("chargeBeginUserID <=", value, "chargebeginuserid");
            return (Criteria) this;
        }

        public Criteria andChargebeginuseridIn(List<Short> values) {
            addCriterion("chargeBeginUserID in", values, "chargebeginuserid");
            return (Criteria) this;
        }

        public Criteria andChargebeginuseridNotIn(List<Short> values) {
            addCriterion("chargeBeginUserID not in", values, "chargebeginuserid");
            return (Criteria) this;
        }

        public Criteria andChargebeginuseridBetween(Short value1, Short value2) {
            addCriterion("chargeBeginUserID between", value1, value2, "chargebeginuserid");
            return (Criteria) this;
        }

        public Criteria andChargebeginuseridNotBetween(Short value1, Short value2) {
            addCriterion("chargeBeginUserID not between", value1, value2, "chargebeginuserid");
            return (Criteria) this;
        }

        public Criteria andChargetypeIsNull() {
            addCriterion("chargeType is null");
            return (Criteria) this;
        }

        public Criteria andChargetypeIsNotNull() {
            addCriterion("chargeType is not null");
            return (Criteria) this;
        }

        public Criteria andChargetypeEqualTo(Byte value) {
            addCriterion("chargeType =", value, "chargetype");
            return (Criteria) this;
        }

        public Criteria andChargetypeNotEqualTo(Byte value) {
            addCriterion("chargeType <>", value, "chargetype");
            return (Criteria) this;
        }

        public Criteria andChargetypeGreaterThan(Byte value) {
            addCriterion("chargeType >", value, "chargetype");
            return (Criteria) this;
        }

        public Criteria andChargetypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("chargeType >=", value, "chargetype");
            return (Criteria) this;
        }

        public Criteria andChargetypeLessThan(Byte value) {
            addCriterion("chargeType <", value, "chargetype");
            return (Criteria) this;
        }

        public Criteria andChargetypeLessThanOrEqualTo(Byte value) {
            addCriterion("chargeType <=", value, "chargetype");
            return (Criteria) this;
        }

        public Criteria andChargetypeIn(List<Byte> values) {
            addCriterion("chargeType in", values, "chargetype");
            return (Criteria) this;
        }

        public Criteria andChargetypeNotIn(List<Byte> values) {
            addCriterion("chargeType not in", values, "chargetype");
            return (Criteria) this;
        }

        public Criteria andChargetypeBetween(Byte value1, Byte value2) {
            addCriterion("chargeType between", value1, value2, "chargetype");
            return (Criteria) this;
        }

        public Criteria andChargetypeNotBetween(Byte value1, Byte value2) {
            addCriterion("chargeType not between", value1, value2, "chargetype");
            return (Criteria) this;
        }

        public Criteria andChargewholepriceIsNull() {
            addCriterion("chargeWholePrice is null");
            return (Criteria) this;
        }

        public Criteria andChargewholepriceIsNotNull() {
            addCriterion("chargeWholePrice is not null");
            return (Criteria) this;
        }

        public Criteria andChargewholepriceEqualTo(Double value) {
            addCriterion("chargeWholePrice =", value, "chargewholeprice");
            return (Criteria) this;
        }

        public Criteria andChargewholepriceNotEqualTo(Double value) {
            addCriterion("chargeWholePrice <>", value, "chargewholeprice");
            return (Criteria) this;
        }

        public Criteria andChargewholepriceGreaterThan(Double value) {
            addCriterion("chargeWholePrice >", value, "chargewholeprice");
            return (Criteria) this;
        }

        public Criteria andChargewholepriceGreaterThanOrEqualTo(Double value) {
            addCriterion("chargeWholePrice >=", value, "chargewholeprice");
            return (Criteria) this;
        }

        public Criteria andChargewholepriceLessThan(Double value) {
            addCriterion("chargeWholePrice <", value, "chargewholeprice");
            return (Criteria) this;
        }

        public Criteria andChargewholepriceLessThanOrEqualTo(Double value) {
            addCriterion("chargeWholePrice <=", value, "chargewholeprice");
            return (Criteria) this;
        }

        public Criteria andChargewholepriceIn(List<Double> values) {
            addCriterion("chargeWholePrice in", values, "chargewholeprice");
            return (Criteria) this;
        }

        public Criteria andChargewholepriceNotIn(List<Double> values) {
            addCriterion("chargeWholePrice not in", values, "chargewholeprice");
            return (Criteria) this;
        }

        public Criteria andChargewholepriceBetween(Double value1, Double value2) {
            addCriterion("chargeWholePrice between", value1, value2, "chargewholeprice");
            return (Criteria) this;
        }

        public Criteria andChargewholepriceNotBetween(Double value1, Double value2) {
            addCriterion("chargeWholePrice not between", value1, value2, "chargewholeprice");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table charge_info
     *
     * @mbg.generated do_not_delete_during_merge Mon Jul 22 16:18:51 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table charge_info
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}