package com.neu.his.pojo;

import java.io.Serializable;

public class DiseaseCatalog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease_catalog.disease_id
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    private Integer diseaseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease_catalog.disease_code
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    private String diseaseCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease_catalog.disease_name
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    private String diseaseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease_catalog.disease_icd
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    private String diseaseIcd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease_catalog.disease_cate_id
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    private Short diseaseCateId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease_catalog.disease_id
     *
     * @return the value of disease_catalog.disease_id
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    public Integer getDiseaseId() {
        return diseaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease_catalog.disease_id
     *
     * @param diseaseId the value for disease_catalog.disease_id
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    public void setDiseaseId(Integer diseaseId) {
        this.diseaseId = diseaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease_catalog.disease_code
     *
     * @return the value of disease_catalog.disease_code
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    public String getDiseaseCode() {
        return diseaseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease_catalog.disease_code
     *
     * @param diseaseCode the value for disease_catalog.disease_code
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    public void setDiseaseCode(String diseaseCode) {
        this.diseaseCode = diseaseCode == null ? null : diseaseCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease_catalog.disease_name
     *
     * @return the value of disease_catalog.disease_name
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    public String getDiseaseName() {
        return diseaseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease_catalog.disease_name
     *
     * @param diseaseName the value for disease_catalog.disease_name
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    public void setDiseaseName(String diseaseName) {
        this.diseaseName = diseaseName == null ? null : diseaseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease_catalog.disease_icd
     *
     * @return the value of disease_catalog.disease_icd
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    public String getDiseaseIcd() {
        return diseaseIcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease_catalog.disease_icd
     *
     * @param diseaseIcd the value for disease_catalog.disease_icd
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    public void setDiseaseIcd(String diseaseIcd) {
        this.diseaseIcd = diseaseIcd == null ? null : diseaseIcd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease_catalog.disease_cate_id
     *
     * @return the value of disease_catalog.disease_cate_id
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    public Short getDiseaseCateId() {
        return diseaseCateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease_catalog.disease_cate_id
     *
     * @param diseaseCateId the value for disease_catalog.disease_cate_id
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    public void setDiseaseCateId(Short diseaseCateId) {
        this.diseaseCateId = diseaseCateId;
    }
}