package com.neu.his.pojo;

import java.util.ArrayList;
import java.util.List;

public class DoctorExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table doctor
     *
     * @mbg.generated Tue Jul 23 16:41:35 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table doctor
     *
     * @mbg.generated Tue Jul 23 16:41:35 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table doctor
     *
     * @mbg.generated Tue Jul 23 16:41:35 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor
     *
     * @mbg.generated Tue Jul 23 16:41:35 CST 2019
     */
    public DoctorExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor
     *
     * @mbg.generated Tue Jul 23 16:41:35 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor
     *
     * @mbg.generated Tue Jul 23 16:41:35 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor
     *
     * @mbg.generated Tue Jul 23 16:41:35 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor
     *
     * @mbg.generated Tue Jul 23 16:41:35 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor
     *
     * @mbg.generated Tue Jul 23 16:41:35 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor
     *
     * @mbg.generated Tue Jul 23 16:41:35 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor
     *
     * @mbg.generated Tue Jul 23 16:41:35 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor
     *
     * @mbg.generated Tue Jul 23 16:41:35 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor
     *
     * @mbg.generated Tue Jul 23 16:41:35 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor
     *
     * @mbg.generated Tue Jul 23 16:41:35 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table doctor
     *
     * @mbg.generated Tue Jul 23 16:41:35 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDoctorIdIsNull() {
            addCriterion("doctor_id is null");
            return (Criteria) this;
        }

        public Criteria andDoctorIdIsNotNull() {
            addCriterion("doctor_id is not null");
            return (Criteria) this;
        }

        public Criteria andDoctorIdEqualTo(Short value) {
            addCriterion("doctor_id =", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdNotEqualTo(Short value) {
            addCriterion("doctor_id <>", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdGreaterThan(Short value) {
            addCriterion("doctor_id >", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdGreaterThanOrEqualTo(Short value) {
            addCriterion("doctor_id >=", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdLessThan(Short value) {
            addCriterion("doctor_id <", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdLessThanOrEqualTo(Short value) {
            addCriterion("doctor_id <=", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdIn(List<Short> values) {
            addCriterion("doctor_id in", values, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdNotIn(List<Short> values) {
            addCriterion("doctor_id not in", values, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdBetween(Short value1, Short value2) {
            addCriterion("doctor_id between", value1, value2, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdNotBetween(Short value1, Short value2) {
            addCriterion("doctor_id not between", value1, value2, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorLoginNameIsNull() {
            addCriterion("doctor_login_name is null");
            return (Criteria) this;
        }

        public Criteria andDoctorLoginNameIsNotNull() {
            addCriterion("doctor_login_name is not null");
            return (Criteria) this;
        }

        public Criteria andDoctorLoginNameEqualTo(String value) {
            addCriterion("doctor_login_name =", value, "doctorLoginName");
            return (Criteria) this;
        }

        public Criteria andDoctorLoginNameNotEqualTo(String value) {
            addCriterion("doctor_login_name <>", value, "doctorLoginName");
            return (Criteria) this;
        }

        public Criteria andDoctorLoginNameGreaterThan(String value) {
            addCriterion("doctor_login_name >", value, "doctorLoginName");
            return (Criteria) this;
        }

        public Criteria andDoctorLoginNameGreaterThanOrEqualTo(String value) {
            addCriterion("doctor_login_name >=", value, "doctorLoginName");
            return (Criteria) this;
        }

        public Criteria andDoctorLoginNameLessThan(String value) {
            addCriterion("doctor_login_name <", value, "doctorLoginName");
            return (Criteria) this;
        }

        public Criteria andDoctorLoginNameLessThanOrEqualTo(String value) {
            addCriterion("doctor_login_name <=", value, "doctorLoginName");
            return (Criteria) this;
        }

        public Criteria andDoctorLoginNameLike(String value) {
            addCriterion("doctor_login_name like", value, "doctorLoginName");
            return (Criteria) this;
        }

        public Criteria andDoctorLoginNameNotLike(String value) {
            addCriterion("doctor_login_name not like", value, "doctorLoginName");
            return (Criteria) this;
        }

        public Criteria andDoctorLoginNameIn(List<String> values) {
            addCriterion("doctor_login_name in", values, "doctorLoginName");
            return (Criteria) this;
        }

        public Criteria andDoctorLoginNameNotIn(List<String> values) {
            addCriterion("doctor_login_name not in", values, "doctorLoginName");
            return (Criteria) this;
        }

        public Criteria andDoctorLoginNameBetween(String value1, String value2) {
            addCriterion("doctor_login_name between", value1, value2, "doctorLoginName");
            return (Criteria) this;
        }

        public Criteria andDoctorLoginNameNotBetween(String value1, String value2) {
            addCriterion("doctor_login_name not between", value1, value2, "doctorLoginName");
            return (Criteria) this;
        }

        public Criteria andDoctorPswIsNull() {
            addCriterion("doctor_psw is null");
            return (Criteria) this;
        }

        public Criteria andDoctorPswIsNotNull() {
            addCriterion("doctor_psw is not null");
            return (Criteria) this;
        }

        public Criteria andDoctorPswEqualTo(String value) {
            addCriterion("doctor_psw =", value, "doctorPsw");
            return (Criteria) this;
        }

        public Criteria andDoctorPswNotEqualTo(String value) {
            addCriterion("doctor_psw <>", value, "doctorPsw");
            return (Criteria) this;
        }

        public Criteria andDoctorPswGreaterThan(String value) {
            addCriterion("doctor_psw >", value, "doctorPsw");
            return (Criteria) this;
        }

        public Criteria andDoctorPswGreaterThanOrEqualTo(String value) {
            addCriterion("doctor_psw >=", value, "doctorPsw");
            return (Criteria) this;
        }

        public Criteria andDoctorPswLessThan(String value) {
            addCriterion("doctor_psw <", value, "doctorPsw");
            return (Criteria) this;
        }

        public Criteria andDoctorPswLessThanOrEqualTo(String value) {
            addCriterion("doctor_psw <=", value, "doctorPsw");
            return (Criteria) this;
        }

        public Criteria andDoctorPswLike(String value) {
            addCriterion("doctor_psw like", value, "doctorPsw");
            return (Criteria) this;
        }

        public Criteria andDoctorPswNotLike(String value) {
            addCriterion("doctor_psw not like", value, "doctorPsw");
            return (Criteria) this;
        }

        public Criteria andDoctorPswIn(List<String> values) {
            addCriterion("doctor_psw in", values, "doctorPsw");
            return (Criteria) this;
        }

        public Criteria andDoctorPswNotIn(List<String> values) {
            addCriterion("doctor_psw not in", values, "doctorPsw");
            return (Criteria) this;
        }

        public Criteria andDoctorPswBetween(String value1, String value2) {
            addCriterion("doctor_psw between", value1, value2, "doctorPsw");
            return (Criteria) this;
        }

        public Criteria andDoctorPswNotBetween(String value1, String value2) {
            addCriterion("doctor_psw not between", value1, value2, "doctorPsw");
            return (Criteria) this;
        }

        public Criteria andDoctorNameIsNull() {
            addCriterion("doctor_name is null");
            return (Criteria) this;
        }

        public Criteria andDoctorNameIsNotNull() {
            addCriterion("doctor_name is not null");
            return (Criteria) this;
        }

        public Criteria andDoctorNameEqualTo(String value) {
            addCriterion("doctor_name =", value, "doctorName");
            return (Criteria) this;
        }

        public Criteria andDoctorNameNotEqualTo(String value) {
            addCriterion("doctor_name <>", value, "doctorName");
            return (Criteria) this;
        }

        public Criteria andDoctorNameGreaterThan(String value) {
            addCriterion("doctor_name >", value, "doctorName");
            return (Criteria) this;
        }

        public Criteria andDoctorNameGreaterThanOrEqualTo(String value) {
            addCriterion("doctor_name >=", value, "doctorName");
            return (Criteria) this;
        }

        public Criteria andDoctorNameLessThan(String value) {
            addCriterion("doctor_name <", value, "doctorName");
            return (Criteria) this;
        }

        public Criteria andDoctorNameLessThanOrEqualTo(String value) {
            addCriterion("doctor_name <=", value, "doctorName");
            return (Criteria) this;
        }

        public Criteria andDoctorNameLike(String value) {
            addCriterion("doctor_name like", value, "doctorName");
            return (Criteria) this;
        }

        public Criteria andDoctorNameNotLike(String value) {
            addCriterion("doctor_name not like", value, "doctorName");
            return (Criteria) this;
        }

        public Criteria andDoctorNameIn(List<String> values) {
            addCriterion("doctor_name in", values, "doctorName");
            return (Criteria) this;
        }

        public Criteria andDoctorNameNotIn(List<String> values) {
            addCriterion("doctor_name not in", values, "doctorName");
            return (Criteria) this;
        }

        public Criteria andDoctorNameBetween(String value1, String value2) {
            addCriterion("doctor_name between", value1, value2, "doctorName");
            return (Criteria) this;
        }

        public Criteria andDoctorNameNotBetween(String value1, String value2) {
            addCriterion("doctor_name not between", value1, value2, "doctorName");
            return (Criteria) this;
        }

        public Criteria andDeptIdIsNull() {
            addCriterion("dept_id is null");
            return (Criteria) this;
        }

        public Criteria andDeptIdIsNotNull() {
            addCriterion("dept_id is not null");
            return (Criteria) this;
        }

        public Criteria andDeptIdEqualTo(Short value) {
            addCriterion("dept_id =", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotEqualTo(Short value) {
            addCriterion("dept_id <>", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdGreaterThan(Short value) {
            addCriterion("dept_id >", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdGreaterThanOrEqualTo(Short value) {
            addCriterion("dept_id >=", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdLessThan(Short value) {
            addCriterion("dept_id <", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdLessThanOrEqualTo(Short value) {
            addCriterion("dept_id <=", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdIn(List<Short> values) {
            addCriterion("dept_id in", values, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotIn(List<Short> values) {
            addCriterion("dept_id not in", values, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdBetween(Short value1, Short value2) {
            addCriterion("dept_id between", value1, value2, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotBetween(Short value1, Short value2) {
            addCriterion("dept_id not between", value1, value2, "deptId");
            return (Criteria) this;
        }

        public Criteria andDoctorTypeIsNull() {
            addCriterion("doctor_type is null");
            return (Criteria) this;
        }

        public Criteria andDoctorTypeIsNotNull() {
            addCriterion("doctor_type is not null");
            return (Criteria) this;
        }

        public Criteria andDoctorTypeEqualTo(Short value) {
            addCriterion("doctor_type =", value, "doctorType");
            return (Criteria) this;
        }

        public Criteria andDoctorTypeNotEqualTo(Short value) {
            addCriterion("doctor_type <>", value, "doctorType");
            return (Criteria) this;
        }

        public Criteria andDoctorTypeGreaterThan(Short value) {
            addCriterion("doctor_type >", value, "doctorType");
            return (Criteria) this;
        }

        public Criteria andDoctorTypeGreaterThanOrEqualTo(Short value) {
            addCriterion("doctor_type >=", value, "doctorType");
            return (Criteria) this;
        }

        public Criteria andDoctorTypeLessThan(Short value) {
            addCriterion("doctor_type <", value, "doctorType");
            return (Criteria) this;
        }

        public Criteria andDoctorTypeLessThanOrEqualTo(Short value) {
            addCriterion("doctor_type <=", value, "doctorType");
            return (Criteria) this;
        }

        public Criteria andDoctorTypeIn(List<Short> values) {
            addCriterion("doctor_type in", values, "doctorType");
            return (Criteria) this;
        }

        public Criteria andDoctorTypeNotIn(List<Short> values) {
            addCriterion("doctor_type not in", values, "doctorType");
            return (Criteria) this;
        }

        public Criteria andDoctorTypeBetween(Short value1, Short value2) {
            addCriterion("doctor_type between", value1, value2, "doctorType");
            return (Criteria) this;
        }

        public Criteria andDoctorTypeNotBetween(Short value1, Short value2) {
            addCriterion("doctor_type not between", value1, value2, "doctorType");
            return (Criteria) this;
        }

        public Criteria andDoctorTitleIsNull() {
            addCriterion("doctor_title is null");
            return (Criteria) this;
        }

        public Criteria andDoctorTitleIsNotNull() {
            addCriterion("doctor_title is not null");
            return (Criteria) this;
        }

        public Criteria andDoctorTitleEqualTo(Byte value) {
            addCriterion("doctor_title =", value, "doctorTitle");
            return (Criteria) this;
        }

        public Criteria andDoctorTitleNotEqualTo(Byte value) {
            addCriterion("doctor_title <>", value, "doctorTitle");
            return (Criteria) this;
        }

        public Criteria andDoctorTitleGreaterThan(Byte value) {
            addCriterion("doctor_title >", value, "doctorTitle");
            return (Criteria) this;
        }

        public Criteria andDoctorTitleGreaterThanOrEqualTo(Byte value) {
            addCriterion("doctor_title >=", value, "doctorTitle");
            return (Criteria) this;
        }

        public Criteria andDoctorTitleLessThan(Byte value) {
            addCriterion("doctor_title <", value, "doctorTitle");
            return (Criteria) this;
        }

        public Criteria andDoctorTitleLessThanOrEqualTo(Byte value) {
            addCriterion("doctor_title <=", value, "doctorTitle");
            return (Criteria) this;
        }

        public Criteria andDoctorTitleIn(List<Byte> values) {
            addCriterion("doctor_title in", values, "doctorTitle");
            return (Criteria) this;
        }

        public Criteria andDoctorTitleNotIn(List<Byte> values) {
            addCriterion("doctor_title not in", values, "doctorTitle");
            return (Criteria) this;
        }

        public Criteria andDoctorTitleBetween(Byte value1, Byte value2) {
            addCriterion("doctor_title between", value1, value2, "doctorTitle");
            return (Criteria) this;
        }

        public Criteria andDoctorTitleNotBetween(Byte value1, Byte value2) {
            addCriterion("doctor_title not between", value1, value2, "doctorTitle");
            return (Criteria) this;
        }

        public Criteria andDoctorScheIsNull() {
            addCriterion("doctor_sche is null");
            return (Criteria) this;
        }

        public Criteria andDoctorScheIsNotNull() {
            addCriterion("doctor_sche is not null");
            return (Criteria) this;
        }

        public Criteria andDoctorScheEqualTo(Boolean value) {
            addCriterion("doctor_sche =", value, "doctorSche");
            return (Criteria) this;
        }

        public Criteria andDoctorScheNotEqualTo(Boolean value) {
            addCriterion("doctor_sche <>", value, "doctorSche");
            return (Criteria) this;
        }

        public Criteria andDoctorScheGreaterThan(Boolean value) {
            addCriterion("doctor_sche >", value, "doctorSche");
            return (Criteria) this;
        }

        public Criteria andDoctorScheGreaterThanOrEqualTo(Boolean value) {
            addCriterion("doctor_sche >=", value, "doctorSche");
            return (Criteria) this;
        }

        public Criteria andDoctorScheLessThan(Boolean value) {
            addCriterion("doctor_sche <", value, "doctorSche");
            return (Criteria) this;
        }

        public Criteria andDoctorScheLessThanOrEqualTo(Boolean value) {
            addCriterion("doctor_sche <=", value, "doctorSche");
            return (Criteria) this;
        }

        public Criteria andDoctorScheIn(List<Boolean> values) {
            addCriterion("doctor_sche in", values, "doctorSche");
            return (Criteria) this;
        }

        public Criteria andDoctorScheNotIn(List<Boolean> values) {
            addCriterion("doctor_sche not in", values, "doctorSche");
            return (Criteria) this;
        }

        public Criteria andDoctorScheBetween(Boolean value1, Boolean value2) {
            addCriterion("doctor_sche between", value1, value2, "doctorSche");
            return (Criteria) this;
        }

        public Criteria andDoctorScheNotBetween(Boolean value1, Boolean value2) {
            addCriterion("doctor_sche not between", value1, value2, "doctorSche");
            return (Criteria) this;
        }

        public Criteria andDoctorRegistLevelIsNull() {
            addCriterion("doctor_regist_level is null");
            return (Criteria) this;
        }

        public Criteria andDoctorRegistLevelIsNotNull() {
            addCriterion("doctor_regist_level is not null");
            return (Criteria) this;
        }

        public Criteria andDoctorRegistLevelEqualTo(Boolean value) {
            addCriterion("doctor_regist_level =", value, "doctorRegistLevel");
            return (Criteria) this;
        }

        public Criteria andDoctorRegistLevelNotEqualTo(Boolean value) {
            addCriterion("doctor_regist_level <>", value, "doctorRegistLevel");
            return (Criteria) this;
        }

        public Criteria andDoctorRegistLevelGreaterThan(Boolean value) {
            addCriterion("doctor_regist_level >", value, "doctorRegistLevel");
            return (Criteria) this;
        }

        public Criteria andDoctorRegistLevelGreaterThanOrEqualTo(Boolean value) {
            addCriterion("doctor_regist_level >=", value, "doctorRegistLevel");
            return (Criteria) this;
        }

        public Criteria andDoctorRegistLevelLessThan(Boolean value) {
            addCriterion("doctor_regist_level <", value, "doctorRegistLevel");
            return (Criteria) this;
        }

        public Criteria andDoctorRegistLevelLessThanOrEqualTo(Boolean value) {
            addCriterion("doctor_regist_level <=", value, "doctorRegistLevel");
            return (Criteria) this;
        }

        public Criteria andDoctorRegistLevelIn(List<Boolean> values) {
            addCriterion("doctor_regist_level in", values, "doctorRegistLevel");
            return (Criteria) this;
        }

        public Criteria andDoctorRegistLevelNotIn(List<Boolean> values) {
            addCriterion("doctor_regist_level not in", values, "doctorRegistLevel");
            return (Criteria) this;
        }

        public Criteria andDoctorRegistLevelBetween(Boolean value1, Boolean value2) {
            addCriterion("doctor_regist_level between", value1, value2, "doctorRegistLevel");
            return (Criteria) this;
        }

        public Criteria andDoctorRegistLevelNotBetween(Boolean value1, Boolean value2) {
            addCriterion("doctor_regist_level not between", value1, value2, "doctorRegistLevel");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table doctor
     *
     * @mbg.generated do_not_delete_during_merge Tue Jul 23 16:41:35 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table doctor
     *
     * @mbg.generated Tue Jul 23 16:41:35 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}