package com.neu.his.pojo;

import java.io.Serializable;

public class DrugTemplate implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_template.drug_temp_id
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    private Short drugTempId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_template.doctor_id
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    private Short doctorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_template.drug_code
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    private Short drugCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_template.drug_specif
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    private String drugSpecif;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_template.drug_price
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    private Double drugPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_template.drug_usage
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    private String drugUsage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_template.drug_dosage
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    private String drugDosage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_template.drug_freq
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    private String drugFreq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_template.drug_amount
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    private Byte drugAmount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_template.drug_temp_id
     *
     * @return the value of drug_template.drug_temp_id
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    public Short getDrugTempId() {
        return drugTempId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_template.drug_temp_id
     *
     * @param drugTempId the value for drug_template.drug_temp_id
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    public void setDrugTempId(Short drugTempId) {
        this.drugTempId = drugTempId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_template.doctor_id
     *
     * @return the value of drug_template.doctor_id
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    public Short getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_template.doctor_id
     *
     * @param doctorId the value for drug_template.doctor_id
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    public void setDoctorId(Short doctorId) {
        this.doctorId = doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_template.drug_code
     *
     * @return the value of drug_template.drug_code
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    public Short getDrugCode() {
        return drugCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_template.drug_code
     *
     * @param drugCode the value for drug_template.drug_code
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    public void setDrugCode(Short drugCode) {
        this.drugCode = drugCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_template.drug_specif
     *
     * @return the value of drug_template.drug_specif
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    public String getDrugSpecif() {
        return drugSpecif;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_template.drug_specif
     *
     * @param drugSpecif the value for drug_template.drug_specif
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    public void setDrugSpecif(String drugSpecif) {
        this.drugSpecif = drugSpecif == null ? null : drugSpecif.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_template.drug_price
     *
     * @return the value of drug_template.drug_price
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    public Double getDrugPrice() {
        return drugPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_template.drug_price
     *
     * @param drugPrice the value for drug_template.drug_price
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    public void setDrugPrice(Double drugPrice) {
        this.drugPrice = drugPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_template.drug_usage
     *
     * @return the value of drug_template.drug_usage
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    public String getDrugUsage() {
        return drugUsage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_template.drug_usage
     *
     * @param drugUsage the value for drug_template.drug_usage
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    public void setDrugUsage(String drugUsage) {
        this.drugUsage = drugUsage == null ? null : drugUsage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_template.drug_dosage
     *
     * @return the value of drug_template.drug_dosage
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    public String getDrugDosage() {
        return drugDosage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_template.drug_dosage
     *
     * @param drugDosage the value for drug_template.drug_dosage
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    public void setDrugDosage(String drugDosage) {
        this.drugDosage = drugDosage == null ? null : drugDosage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_template.drug_freq
     *
     * @return the value of drug_template.drug_freq
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    public String getDrugFreq() {
        return drugFreq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_template.drug_freq
     *
     * @param drugFreq the value for drug_template.drug_freq
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    public void setDrugFreq(String drugFreq) {
        this.drugFreq = drugFreq == null ? null : drugFreq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_template.drug_amount
     *
     * @return the value of drug_template.drug_amount
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    public Byte getDrugAmount() {
        return drugAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_template.drug_amount
     *
     * @param drugAmount the value for drug_template.drug_amount
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    public void setDrugAmount(Byte drugAmount) {
        this.drugAmount = drugAmount;
    }
}