package com.neu.his.pojo;

public class MedicalRecordWithBLOBs extends MedicalRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medical_record.medical_record_curt_illness
     *
     * @mbg.generated Wed Jul 24 16:06:06 CST 2019
     */
    private String medicalRecordCurtIllness;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medical_record.medical_record_treat
     *
     * @mbg.generated Wed Jul 24 16:06:06 CST 2019
     */
    private String medicalRecordTreat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medical_record.medical_record_pre_illness
     *
     * @mbg.generated Wed Jul 24 16:06:06 CST 2019
     */
    private String medicalRecordPreIllness;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medical_record.medical_record_allergy
     *
     * @mbg.generated Wed Jul 24 16:06:06 CST 2019
     */
    private String medicalRecordAllergy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medical_record.medical_record_check
     *
     * @mbg.generated Wed Jul 24 16:06:06 CST 2019
     */
    private String medicalRecordCheck;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medical_record.medical_record_check_advice
     *
     * @mbg.generated Wed Jul 24 16:06:06 CST 2019
     */
    private String medicalRecordCheckAdvice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medical_record.medical_record_warn
     *
     * @mbg.generated Wed Jul 24 16:06:06 CST 2019
     */
    private String medicalRecordWarn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_record.medical_record_curt_illness
     *
     * @return the value of medical_record.medical_record_curt_illness
     *
     * @mbg.generated Wed Jul 24 16:06:06 CST 2019
     */
    public String getMedicalRecordCurtIllness() {
        return medicalRecordCurtIllness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_record.medical_record_curt_illness
     *
     * @param medicalRecordCurtIllness the value for medical_record.medical_record_curt_illness
     *
     * @mbg.generated Wed Jul 24 16:06:06 CST 2019
     */
    public void setMedicalRecordCurtIllness(String medicalRecordCurtIllness) {
        this.medicalRecordCurtIllness = medicalRecordCurtIllness == null ? null : medicalRecordCurtIllness.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_record.medical_record_treat
     *
     * @return the value of medical_record.medical_record_treat
     *
     * @mbg.generated Wed Jul 24 16:06:06 CST 2019
     */
    public String getMedicalRecordTreat() {
        return medicalRecordTreat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_record.medical_record_treat
     *
     * @param medicalRecordTreat the value for medical_record.medical_record_treat
     *
     * @mbg.generated Wed Jul 24 16:06:06 CST 2019
     */
    public void setMedicalRecordTreat(String medicalRecordTreat) {
        this.medicalRecordTreat = medicalRecordTreat == null ? null : medicalRecordTreat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_record.medical_record_pre_illness
     *
     * @return the value of medical_record.medical_record_pre_illness
     *
     * @mbg.generated Wed Jul 24 16:06:06 CST 2019
     */
    public String getMedicalRecordPreIllness() {
        return medicalRecordPreIllness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_record.medical_record_pre_illness
     *
     * @param medicalRecordPreIllness the value for medical_record.medical_record_pre_illness
     *
     * @mbg.generated Wed Jul 24 16:06:06 CST 2019
     */
    public void setMedicalRecordPreIllness(String medicalRecordPreIllness) {
        this.medicalRecordPreIllness = medicalRecordPreIllness == null ? null : medicalRecordPreIllness.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_record.medical_record_allergy
     *
     * @return the value of medical_record.medical_record_allergy
     *
     * @mbg.generated Wed Jul 24 16:06:06 CST 2019
     */
    public String getMedicalRecordAllergy() {
        return medicalRecordAllergy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_record.medical_record_allergy
     *
     * @param medicalRecordAllergy the value for medical_record.medical_record_allergy
     *
     * @mbg.generated Wed Jul 24 16:06:06 CST 2019
     */
    public void setMedicalRecordAllergy(String medicalRecordAllergy) {
        this.medicalRecordAllergy = medicalRecordAllergy == null ? null : medicalRecordAllergy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_record.medical_record_check
     *
     * @return the value of medical_record.medical_record_check
     *
     * @mbg.generated Wed Jul 24 16:06:06 CST 2019
     */
    public String getMedicalRecordCheck() {
        return medicalRecordCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_record.medical_record_check
     *
     * @param medicalRecordCheck the value for medical_record.medical_record_check
     *
     * @mbg.generated Wed Jul 24 16:06:06 CST 2019
     */
    public void setMedicalRecordCheck(String medicalRecordCheck) {
        this.medicalRecordCheck = medicalRecordCheck == null ? null : medicalRecordCheck.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_record.medical_record_check_advice
     *
     * @return the value of medical_record.medical_record_check_advice
     *
     * @mbg.generated Wed Jul 24 16:06:06 CST 2019
     */
    public String getMedicalRecordCheckAdvice() {
        return medicalRecordCheckAdvice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_record.medical_record_check_advice
     *
     * @param medicalRecordCheckAdvice the value for medical_record.medical_record_check_advice
     *
     * @mbg.generated Wed Jul 24 16:06:06 CST 2019
     */
    public void setMedicalRecordCheckAdvice(String medicalRecordCheckAdvice) {
        this.medicalRecordCheckAdvice = medicalRecordCheckAdvice == null ? null : medicalRecordCheckAdvice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_record.medical_record_warn
     *
     * @return the value of medical_record.medical_record_warn
     *
     * @mbg.generated Wed Jul 24 16:06:06 CST 2019
     */
    public String getMedicalRecordWarn() {
        return medicalRecordWarn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_record.medical_record_warn
     *
     * @param medicalRecordWarn the value for medical_record.medical_record_warn
     *
     * @mbg.generated Wed Jul 24 16:06:06 CST 2019
     */
    public void setMedicalRecordWarn(String medicalRecordWarn) {
        this.medicalRecordWarn = medicalRecordWarn == null ? null : medicalRecordWarn.trim();
    }
}