package com.neu.his.pojo;

import java.io.Serializable;

public class RegistLevel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column regist_level.regist_level_id
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    private Byte registLevelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column regist_level.regist_level_code
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    private String registLevelCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column regist_level.regist_level_name
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    private String registLevelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column regist_level.regist_level_seq
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    private String registLevelSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column regist_level.regist_level_price
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    private Byte registLevelPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column regist_level.regist_level_limit
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    private Byte registLevelLimit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column regist_level.regist_level_id
     *
     * @return the value of regist_level.regist_level_id
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    public Byte getRegistLevelId() {
        return registLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column regist_level.regist_level_id
     *
     * @param registLevelId the value for regist_level.regist_level_id
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    public void setRegistLevelId(Byte registLevelId) {
        this.registLevelId = registLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column regist_level.regist_level_code
     *
     * @return the value of regist_level.regist_level_code
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    public String getRegistLevelCode() {
        return registLevelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column regist_level.regist_level_code
     *
     * @param registLevelCode the value for regist_level.regist_level_code
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    public void setRegistLevelCode(String registLevelCode) {
        this.registLevelCode = registLevelCode == null ? null : registLevelCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column regist_level.regist_level_name
     *
     * @return the value of regist_level.regist_level_name
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    public String getRegistLevelName() {
        return registLevelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column regist_level.regist_level_name
     *
     * @param registLevelName the value for regist_level.regist_level_name
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    public void setRegistLevelName(String registLevelName) {
        this.registLevelName = registLevelName == null ? null : registLevelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column regist_level.regist_level_seq
     *
     * @return the value of regist_level.regist_level_seq
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    public String getRegistLevelSeq() {
        return registLevelSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column regist_level.regist_level_seq
     *
     * @param registLevelSeq the value for regist_level.regist_level_seq
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    public void setRegistLevelSeq(String registLevelSeq) {
        this.registLevelSeq = registLevelSeq == null ? null : registLevelSeq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column regist_level.regist_level_price
     *
     * @return the value of regist_level.regist_level_price
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    public Byte getRegistLevelPrice() {
        return registLevelPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column regist_level.regist_level_price
     *
     * @param registLevelPrice the value for regist_level.regist_level_price
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    public void setRegistLevelPrice(Byte registLevelPrice) {
        this.registLevelPrice = registLevelPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column regist_level.regist_level_limit
     *
     * @return the value of regist_level.regist_level_limit
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    public Byte getRegistLevelLimit() {
        return registLevelLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column regist_level.regist_level_limit
     *
     * @param registLevelLimit the value for regist_level.regist_level_limit
     *
     * @mbg.generated Mon Jul 22 23:45:36 CST 2019
     */
    public void setRegistLevelLimit(Byte registLevelLimit) {
        this.registLevelLimit = registLevelLimit;
    }
}