package com.neu.his.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class RegistrationRecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table registration_record
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table registration_record
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table registration_record
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration_record
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    public RegistrationRecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration_record
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration_record
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration_record
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration_record
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration_record
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration_record
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration_record
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration_record
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration_record
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration_record
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table registration_record
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andRegistIdIsNull() {
            addCriterion("regist_id is null");
            return (Criteria) this;
        }

        public Criteria andRegistIdIsNotNull() {
            addCriterion("regist_id is not null");
            return (Criteria) this;
        }

        public Criteria andRegistIdEqualTo(Integer value) {
            addCriterion("regist_id =", value, "registId");
            return (Criteria) this;
        }

        public Criteria andRegistIdNotEqualTo(Integer value) {
            addCriterion("regist_id <>", value, "registId");
            return (Criteria) this;
        }

        public Criteria andRegistIdGreaterThan(Integer value) {
            addCriterion("regist_id >", value, "registId");
            return (Criteria) this;
        }

        public Criteria andRegistIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("regist_id >=", value, "registId");
            return (Criteria) this;
        }

        public Criteria andRegistIdLessThan(Integer value) {
            addCriterion("regist_id <", value, "registId");
            return (Criteria) this;
        }

        public Criteria andRegistIdLessThanOrEqualTo(Integer value) {
            addCriterion("regist_id <=", value, "registId");
            return (Criteria) this;
        }

        public Criteria andRegistIdIn(List<Integer> values) {
            addCriterion("regist_id in", values, "registId");
            return (Criteria) this;
        }

        public Criteria andRegistIdNotIn(List<Integer> values) {
            addCriterion("regist_id not in", values, "registId");
            return (Criteria) this;
        }

        public Criteria andRegistIdBetween(Integer value1, Integer value2) {
            addCriterion("regist_id between", value1, value2, "registId");
            return (Criteria) this;
        }

        public Criteria andRegistIdNotBetween(Integer value1, Integer value2) {
            addCriterion("regist_id not between", value1, value2, "registId");
            return (Criteria) this;
        }

        public Criteria andPatientRecordIdIsNull() {
            addCriterion("patient_record_id is null");
            return (Criteria) this;
        }

        public Criteria andPatientRecordIdIsNotNull() {
            addCriterion("patient_record_id is not null");
            return (Criteria) this;
        }

        public Criteria andPatientRecordIdEqualTo(Integer value) {
            addCriterion("patient_record_id =", value, "patientRecordId");
            return (Criteria) this;
        }

        public Criteria andPatientRecordIdNotEqualTo(Integer value) {
            addCriterion("patient_record_id <>", value, "patientRecordId");
            return (Criteria) this;
        }

        public Criteria andPatientRecordIdGreaterThan(Integer value) {
            addCriterion("patient_record_id >", value, "patientRecordId");
            return (Criteria) this;
        }

        public Criteria andPatientRecordIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("patient_record_id >=", value, "patientRecordId");
            return (Criteria) this;
        }

        public Criteria andPatientRecordIdLessThan(Integer value) {
            addCriterion("patient_record_id <", value, "patientRecordId");
            return (Criteria) this;
        }

        public Criteria andPatientRecordIdLessThanOrEqualTo(Integer value) {
            addCriterion("patient_record_id <=", value, "patientRecordId");
            return (Criteria) this;
        }

        public Criteria andPatientRecordIdIn(List<Integer> values) {
            addCriterion("patient_record_id in", values, "patientRecordId");
            return (Criteria) this;
        }

        public Criteria andPatientRecordIdNotIn(List<Integer> values) {
            addCriterion("patient_record_id not in", values, "patientRecordId");
            return (Criteria) this;
        }

        public Criteria andPatientRecordIdBetween(Integer value1, Integer value2) {
            addCriterion("patient_record_id between", value1, value2, "patientRecordId");
            return (Criteria) this;
        }

        public Criteria andPatientRecordIdNotBetween(Integer value1, Integer value2) {
            addCriterion("patient_record_id not between", value1, value2, "patientRecordId");
            return (Criteria) this;
        }

        public Criteria andRegistChargeCategoryIsNull() {
            addCriterion("regist_charge_category is null");
            return (Criteria) this;
        }

        public Criteria andRegistChargeCategoryIsNotNull() {
            addCriterion("regist_charge_category is not null");
            return (Criteria) this;
        }

        public Criteria andRegistChargeCategoryEqualTo(Boolean value) {
            addCriterion("regist_charge_category =", value, "registChargeCategory");
            return (Criteria) this;
        }

        public Criteria andRegistChargeCategoryNotEqualTo(Boolean value) {
            addCriterion("regist_charge_category <>", value, "registChargeCategory");
            return (Criteria) this;
        }

        public Criteria andRegistChargeCategoryGreaterThan(Boolean value) {
            addCriterion("regist_charge_category >", value, "registChargeCategory");
            return (Criteria) this;
        }

        public Criteria andRegistChargeCategoryGreaterThanOrEqualTo(Boolean value) {
            addCriterion("regist_charge_category >=", value, "registChargeCategory");
            return (Criteria) this;
        }

        public Criteria andRegistChargeCategoryLessThan(Boolean value) {
            addCriterion("regist_charge_category <", value, "registChargeCategory");
            return (Criteria) this;
        }

        public Criteria andRegistChargeCategoryLessThanOrEqualTo(Boolean value) {
            addCriterion("regist_charge_category <=", value, "registChargeCategory");
            return (Criteria) this;
        }

        public Criteria andRegistChargeCategoryIn(List<Boolean> values) {
            addCriterion("regist_charge_category in", values, "registChargeCategory");
            return (Criteria) this;
        }

        public Criteria andRegistChargeCategoryNotIn(List<Boolean> values) {
            addCriterion("regist_charge_category not in", values, "registChargeCategory");
            return (Criteria) this;
        }

        public Criteria andRegistChargeCategoryBetween(Boolean value1, Boolean value2) {
            addCriterion("regist_charge_category between", value1, value2, "registChargeCategory");
            return (Criteria) this;
        }

        public Criteria andRegistChargeCategoryNotBetween(Boolean value1, Boolean value2) {
            addCriterion("regist_charge_category not between", value1, value2, "registChargeCategory");
            return (Criteria) this;
        }

        public Criteria andRegistLevelIsNull() {
            addCriterion("regist_level is null");
            return (Criteria) this;
        }

        public Criteria andRegistLevelIsNotNull() {
            addCriterion("regist_level is not null");
            return (Criteria) this;
        }

        public Criteria andRegistLevelEqualTo(Boolean value) {
            addCriterion("regist_level =", value, "registLevel");
            return (Criteria) this;
        }

        public Criteria andRegistLevelNotEqualTo(Boolean value) {
            addCriterion("regist_level <>", value, "registLevel");
            return (Criteria) this;
        }

        public Criteria andRegistLevelGreaterThan(Boolean value) {
            addCriterion("regist_level >", value, "registLevel");
            return (Criteria) this;
        }

        public Criteria andRegistLevelGreaterThanOrEqualTo(Boolean value) {
            addCriterion("regist_level >=", value, "registLevel");
            return (Criteria) this;
        }

        public Criteria andRegistLevelLessThan(Boolean value) {
            addCriterion("regist_level <", value, "registLevel");
            return (Criteria) this;
        }

        public Criteria andRegistLevelLessThanOrEqualTo(Boolean value) {
            addCriterion("regist_level <=", value, "registLevel");
            return (Criteria) this;
        }

        public Criteria andRegistLevelIn(List<Boolean> values) {
            addCriterion("regist_level in", values, "registLevel");
            return (Criteria) this;
        }

        public Criteria andRegistLevelNotIn(List<Boolean> values) {
            addCriterion("regist_level not in", values, "registLevel");
            return (Criteria) this;
        }

        public Criteria andRegistLevelBetween(Boolean value1, Boolean value2) {
            addCriterion("regist_level between", value1, value2, "registLevel");
            return (Criteria) this;
        }

        public Criteria andRegistLevelNotBetween(Boolean value1, Boolean value2) {
            addCriterion("regist_level not between", value1, value2, "registLevel");
            return (Criteria) this;
        }

        public Criteria andDoctorIdIsNull() {
            addCriterion("doctor_id is null");
            return (Criteria) this;
        }

        public Criteria andDoctorIdIsNotNull() {
            addCriterion("doctor_id is not null");
            return (Criteria) this;
        }

        public Criteria andDoctorIdEqualTo(Short value) {
            addCriterion("doctor_id =", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdNotEqualTo(Short value) {
            addCriterion("doctor_id <>", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdGreaterThan(Short value) {
            addCriterion("doctor_id >", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdGreaterThanOrEqualTo(Short value) {
            addCriterion("doctor_id >=", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdLessThan(Short value) {
            addCriterion("doctor_id <", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdLessThanOrEqualTo(Short value) {
            addCriterion("doctor_id <=", value, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdIn(List<Short> values) {
            addCriterion("doctor_id in", values, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdNotIn(List<Short> values) {
            addCriterion("doctor_id not in", values, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdBetween(Short value1, Short value2) {
            addCriterion("doctor_id between", value1, value2, "doctorId");
            return (Criteria) this;
        }

        public Criteria andDoctorIdNotBetween(Short value1, Short value2) {
            addCriterion("doctor_id not between", value1, value2, "doctorId");
            return (Criteria) this;
        }

        public Criteria andRegistBookIsNull() {
            addCriterion("regist_book is null");
            return (Criteria) this;
        }

        public Criteria andRegistBookIsNotNull() {
            addCriterion("regist_book is not null");
            return (Criteria) this;
        }

        public Criteria andRegistBookEqualTo(Boolean value) {
            addCriterion("regist_book =", value, "registBook");
            return (Criteria) this;
        }

        public Criteria andRegistBookNotEqualTo(Boolean value) {
            addCriterion("regist_book <>", value, "registBook");
            return (Criteria) this;
        }

        public Criteria andRegistBookGreaterThan(Boolean value) {
            addCriterion("regist_book >", value, "registBook");
            return (Criteria) this;
        }

        public Criteria andRegistBookGreaterThanOrEqualTo(Boolean value) {
            addCriterion("regist_book >=", value, "registBook");
            return (Criteria) this;
        }

        public Criteria andRegistBookLessThan(Boolean value) {
            addCriterion("regist_book <", value, "registBook");
            return (Criteria) this;
        }

        public Criteria andRegistBookLessThanOrEqualTo(Boolean value) {
            addCriterion("regist_book <=", value, "registBook");
            return (Criteria) this;
        }

        public Criteria andRegistBookIn(List<Boolean> values) {
            addCriterion("regist_book in", values, "registBook");
            return (Criteria) this;
        }

        public Criteria andRegistBookNotIn(List<Boolean> values) {
            addCriterion("regist_book not in", values, "registBook");
            return (Criteria) this;
        }

        public Criteria andRegistBookBetween(Boolean value1, Boolean value2) {
            addCriterion("regist_book between", value1, value2, "registBook");
            return (Criteria) this;
        }

        public Criteria andRegistBookNotBetween(Boolean value1, Boolean value2) {
            addCriterion("regist_book not between", value1, value2, "registBook");
            return (Criteria) this;
        }

        public Criteria andRegistStateIsNull() {
            addCriterion("regist_state is null");
            return (Criteria) this;
        }

        public Criteria andRegistStateIsNotNull() {
            addCriterion("regist_state is not null");
            return (Criteria) this;
        }

        public Criteria andRegistStateEqualTo(String value) {
            addCriterion("regist_state =", value, "registState");
            return (Criteria) this;
        }

        public Criteria andRegistStateNotEqualTo(String value) {
            addCriterion("regist_state <>", value, "registState");
            return (Criteria) this;
        }

        public Criteria andRegistStateGreaterThan(String value) {
            addCriterion("regist_state >", value, "registState");
            return (Criteria) this;
        }

        public Criteria andRegistStateGreaterThanOrEqualTo(String value) {
            addCriterion("regist_state >=", value, "registState");
            return (Criteria) this;
        }

        public Criteria andRegistStateLessThan(String value) {
            addCriterion("regist_state <", value, "registState");
            return (Criteria) this;
        }

        public Criteria andRegistStateLessThanOrEqualTo(String value) {
            addCriterion("regist_state <=", value, "registState");
            return (Criteria) this;
        }

        public Criteria andRegistStateLike(String value) {
            addCriterion("regist_state like", value, "registState");
            return (Criteria) this;
        }

        public Criteria andRegistStateNotLike(String value) {
            addCriterion("regist_state not like", value, "registState");
            return (Criteria) this;
        }

        public Criteria andRegistStateIn(List<String> values) {
            addCriterion("regist_state in", values, "registState");
            return (Criteria) this;
        }

        public Criteria andRegistStateNotIn(List<String> values) {
            addCriterion("regist_state not in", values, "registState");
            return (Criteria) this;
        }

        public Criteria andRegistStateBetween(String value1, String value2) {
            addCriterion("regist_state between", value1, value2, "registState");
            return (Criteria) this;
        }

        public Criteria andRegistStateNotBetween(String value1, String value2) {
            addCriterion("regist_state not between", value1, value2, "registState");
            return (Criteria) this;
        }

        public Criteria andRegistTimeIsNull() {
            addCriterion("regist_time is null");
            return (Criteria) this;
        }

        public Criteria andRegistTimeIsNotNull() {
            addCriterion("regist_time is not null");
            return (Criteria) this;
        }

        public Criteria andRegistTimeEqualTo(Date value) {
            addCriterion("regist_time =", value, "registTime");
            return (Criteria) this;
        }

        public Criteria andRegistTimeNotEqualTo(Date value) {
            addCriterion("regist_time <>", value, "registTime");
            return (Criteria) this;
        }

        public Criteria andRegistTimeGreaterThan(Date value) {
            addCriterion("regist_time >", value, "registTime");
            return (Criteria) this;
        }

        public Criteria andRegistTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("regist_time >=", value, "registTime");
            return (Criteria) this;
        }

        public Criteria andRegistTimeLessThan(Date value) {
            addCriterion("regist_time <", value, "registTime");
            return (Criteria) this;
        }

        public Criteria andRegistTimeLessThanOrEqualTo(Date value) {
            addCriterion("regist_time <=", value, "registTime");
            return (Criteria) this;
        }

        public Criteria andRegistTimeIn(List<Date> values) {
            addCriterion("regist_time in", values, "registTime");
            return (Criteria) this;
        }

        public Criteria andRegistTimeNotIn(List<Date> values) {
            addCriterion("regist_time not in", values, "registTime");
            return (Criteria) this;
        }

        public Criteria andRegistTimeBetween(Date value1, Date value2) {
            addCriterion("regist_time between", value1, value2, "registTime");
            return (Criteria) this;
        }

        public Criteria andRegistTimeNotBetween(Date value1, Date value2) {
            addCriterion("regist_time not between", value1, value2, "registTime");
            return (Criteria) this;
        }

        public Criteria andRegistUserIdIsNull() {
            addCriterion("regist_user_id is null");
            return (Criteria) this;
        }

        public Criteria andRegistUserIdIsNotNull() {
            addCriterion("regist_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andRegistUserIdEqualTo(Short value) {
            addCriterion("regist_user_id =", value, "registUserId");
            return (Criteria) this;
        }

        public Criteria andRegistUserIdNotEqualTo(Short value) {
            addCriterion("regist_user_id <>", value, "registUserId");
            return (Criteria) this;
        }

        public Criteria andRegistUserIdGreaterThan(Short value) {
            addCriterion("regist_user_id >", value, "registUserId");
            return (Criteria) this;
        }

        public Criteria andRegistUserIdGreaterThanOrEqualTo(Short value) {
            addCriterion("regist_user_id >=", value, "registUserId");
            return (Criteria) this;
        }

        public Criteria andRegistUserIdLessThan(Short value) {
            addCriterion("regist_user_id <", value, "registUserId");
            return (Criteria) this;
        }

        public Criteria andRegistUserIdLessThanOrEqualTo(Short value) {
            addCriterion("regist_user_id <=", value, "registUserId");
            return (Criteria) this;
        }

        public Criteria andRegistUserIdIn(List<Short> values) {
            addCriterion("regist_user_id in", values, "registUserId");
            return (Criteria) this;
        }

        public Criteria andRegistUserIdNotIn(List<Short> values) {
            addCriterion("regist_user_id not in", values, "registUserId");
            return (Criteria) this;
        }

        public Criteria andRegistUserIdBetween(Short value1, Short value2) {
            addCriterion("regist_user_id between", value1, value2, "registUserId");
            return (Criteria) this;
        }

        public Criteria andRegistUserIdNotBetween(Short value1, Short value2) {
            addCriterion("regist_user_id not between", value1, value2, "registUserId");
            return (Criteria) this;
        }

        public Criteria andDeptIdIsNull() {
            addCriterion("dept_id is null");
            return (Criteria) this;
        }

        public Criteria andDeptIdIsNotNull() {
            addCriterion("dept_id is not null");
            return (Criteria) this;
        }

        public Criteria andDeptIdEqualTo(Short value) {
            addCriterion("dept_id =", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotEqualTo(Short value) {
            addCriterion("dept_id <>", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdGreaterThan(Short value) {
            addCriterion("dept_id >", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdGreaterThanOrEqualTo(Short value) {
            addCriterion("dept_id >=", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdLessThan(Short value) {
            addCriterion("dept_id <", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdLessThanOrEqualTo(Short value) {
            addCriterion("dept_id <=", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdIn(List<Short> values) {
            addCriterion("dept_id in", values, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotIn(List<Short> values) {
            addCriterion("dept_id not in", values, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdBetween(Short value1, Short value2) {
            addCriterion("dept_id between", value1, value2, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotBetween(Short value1, Short value2) {
            addCriterion("dept_id not between", value1, value2, "deptId");
            return (Criteria) this;
        }

        public Criteria andRegistNoonIsNull() {
            addCriterion("regist_noon is null");
            return (Criteria) this;
        }

        public Criteria andRegistNoonIsNotNull() {
            addCriterion("regist_noon is not null");
            return (Criteria) this;
        }

        public Criteria andRegistNoonEqualTo(String value) {
            addCriterion("regist_noon =", value, "registNoon");
            return (Criteria) this;
        }

        public Criteria andRegistNoonNotEqualTo(String value) {
            addCriterion("regist_noon <>", value, "registNoon");
            return (Criteria) this;
        }

        public Criteria andRegistNoonGreaterThan(String value) {
            addCriterion("regist_noon >", value, "registNoon");
            return (Criteria) this;
        }

        public Criteria andRegistNoonGreaterThanOrEqualTo(String value) {
            addCriterion("regist_noon >=", value, "registNoon");
            return (Criteria) this;
        }

        public Criteria andRegistNoonLessThan(String value) {
            addCriterion("regist_noon <", value, "registNoon");
            return (Criteria) this;
        }

        public Criteria andRegistNoonLessThanOrEqualTo(String value) {
            addCriterion("regist_noon <=", value, "registNoon");
            return (Criteria) this;
        }

        public Criteria andRegistNoonLike(String value) {
            addCriterion("regist_noon like", value, "registNoon");
            return (Criteria) this;
        }

        public Criteria andRegistNoonNotLike(String value) {
            addCriterion("regist_noon not like", value, "registNoon");
            return (Criteria) this;
        }

        public Criteria andRegistNoonIn(List<String> values) {
            addCriterion("regist_noon in", values, "registNoon");
            return (Criteria) this;
        }

        public Criteria andRegistNoonNotIn(List<String> values) {
            addCriterion("regist_noon not in", values, "registNoon");
            return (Criteria) this;
        }

        public Criteria andRegistNoonBetween(String value1, String value2) {
            addCriterion("regist_noon between", value1, value2, "registNoon");
            return (Criteria) this;
        }

        public Criteria andRegistNoonNotBetween(String value1, String value2) {
            addCriterion("regist_noon not between", value1, value2, "registNoon");
            return (Criteria) this;
        }

        public Criteria andRegistDateIsNull() {
            addCriterion("regist_date is null");
            return (Criteria) this;
        }

        public Criteria andRegistDateIsNotNull() {
            addCriterion("regist_date is not null");
            return (Criteria) this;
        }

        public Criteria andRegistDateEqualTo(Date value) {
            addCriterionForJDBCDate("regist_date =", value, "registDate");
            return (Criteria) this;
        }

        public Criteria andRegistDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("regist_date <>", value, "registDate");
            return (Criteria) this;
        }

        public Criteria andRegistDateGreaterThan(Date value) {
            addCriterionForJDBCDate("regist_date >", value, "registDate");
            return (Criteria) this;
        }

        public Criteria andRegistDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("regist_date >=", value, "registDate");
            return (Criteria) this;
        }

        public Criteria andRegistDateLessThan(Date value) {
            addCriterionForJDBCDate("regist_date <", value, "registDate");
            return (Criteria) this;
        }

        public Criteria andRegistDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("regist_date <=", value, "registDate");
            return (Criteria) this;
        }

        public Criteria andRegistDateIn(List<Date> values) {
            addCriterionForJDBCDate("regist_date in", values, "registDate");
            return (Criteria) this;
        }

        public Criteria andRegistDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("regist_date not in", values, "registDate");
            return (Criteria) this;
        }

        public Criteria andRegistDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("regist_date between", value1, value2, "registDate");
            return (Criteria) this;
        }

        public Criteria andRegistDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("regist_date not between", value1, value2, "registDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table registration_record
     *
     * @mbg.generated do_not_delete_during_merge Mon Jul 22 16:18:51 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table registration_record
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}