package com.neu.his.pojo;

public class ScheRule {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sche_rule.sche_rule_id
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    private Short scheRuleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sche_rule.sche_rule_name
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    private String scheRuleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sche_rule.doctor_id
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    private Short doctorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sche_rule.sche_rule_date
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    private String scheRuleDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sche_rule.sche_day
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    private Float scheDay;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sche_rule.sche_rule_id
     *
     * @return the value of sche_rule.sche_rule_id
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    public Short getScheRuleId() {
        return scheRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sche_rule.sche_rule_id
     *
     * @param scheRuleId the value for sche_rule.sche_rule_id
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    public void setScheRuleId(Short scheRuleId) {
        this.scheRuleId = scheRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sche_rule.sche_rule_name
     *
     * @return the value of sche_rule.sche_rule_name
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    public String getScheRuleName() {
        return scheRuleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sche_rule.sche_rule_name
     *
     * @param scheRuleName the value for sche_rule.sche_rule_name
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    public void setScheRuleName(String scheRuleName) {
        this.scheRuleName = scheRuleName == null ? null : scheRuleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sche_rule.doctor_id
     *
     * @return the value of sche_rule.doctor_id
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    public Short getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sche_rule.doctor_id
     *
     * @param doctorId the value for sche_rule.doctor_id
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    public void setDoctorId(Short doctorId) {
        this.doctorId = doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sche_rule.sche_rule_date
     *
     * @return the value of sche_rule.sche_rule_date
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    public String getScheRuleDate() {
        return scheRuleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sche_rule.sche_rule_date
     *
     * @param scheRuleDate the value for sche_rule.sche_rule_date
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    public void setScheRuleDate(String scheRuleDate) {
        this.scheRuleDate = scheRuleDate == null ? null : scheRuleDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sche_rule.sche_day
     *
     * @return the value of sche_rule.sche_day
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    public Float getScheDay() {
        return scheDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sche_rule.sche_day
     *
     * @param scheDay the value for sche_rule.sche_day
     *
     * @mbg.generated Mon Jul 22 16:18:51 CST 2019
     */
    public void setScheDay(Float scheDay) {
        this.scheDay = scheDay;
    }
}